;; GENERATED by tools/jbob2wat.wat from vendor/j-bob/j-bob.scm (BSD 2-Clause, Friedman and Eastlund). Do not edit by hand.

(:wat::core::def :jb::list0 (:wat::core::quote ()))

(:wat::core::defn :jb::list0? [x <- :wat::WatAST] -> :wat::WatAST (:jb::equal x (:wat::core::quote ())))

(:wat::core::defn :jb::list1 [x <- :wat::WatAST] -> :wat::WatAST (:jb::cons x :jb::list0))

(:wat::core::defn :jb::list1? [x <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::atom x)) (:wat::core::quote nil) (:jb::list0? (:jb::cdr x))))

(:wat::core::defn :jb::elem1 [xs <- :wat::WatAST] -> :wat::WatAST (:jb::car xs))

(:wat::core::defn :jb::list2 [x <- :wat::WatAST y <- :wat::WatAST] -> :wat::WatAST (:jb::cons x (:jb::list1 y)))

(:wat::core::defn :jb::list2? [x <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::atom x)) (:wat::core::quote nil) (:jb::list1? (:jb::cdr x))))

(:wat::core::defn :jb::elem2 [xs <- :wat::WatAST] -> :wat::WatAST (:jb::elem1 (:jb::cdr xs)))

(:wat::core::defn :jb::list3 [x <- :wat::WatAST y <- :wat::WatAST z <- :wat::WatAST] -> :wat::WatAST (:jb::cons x (:jb::list2 y z)))

(:wat::core::defn :jb::list3? [x <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::atom x)) (:wat::core::quote nil) (:jb::list2? (:jb::cdr x))))

(:wat::core::defn :jb::elem3 [xs <- :wat::WatAST] -> :wat::WatAST (:jb::elem2 (:jb::cdr xs)))

(:wat::core::defn :jb::tag [sym <- :wat::WatAST x <- :wat::WatAST] -> :wat::WatAST (:jb::cons sym x))

(:wat::core::defn :jb::tag? [sym <- :wat::WatAST x <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::atom x)) (:wat::core::quote nil) (:jb::equal (:jb::car x) sym)))

(:wat::core::defn :jb::untag [x <- :wat::WatAST] -> :wat::WatAST (:jb::cdr x))

(:wat::core::defn :jb::quote-c [value <- :wat::WatAST] -> :wat::WatAST (:jb::tag (:wat::core::quote quote) (:jb::list1 value)))

(:wat::core::defn :jb::quote? [x <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::tag? (:wat::core::quote quote) x)) (:jb::list1? (:jb::untag x)) (:wat::core::quote nil)))

(:wat::core::defn :jb::quote_value [e <- :wat::WatAST] -> :wat::WatAST (:jb::elem1 (:jb::untag e)))

(:wat::core::defn :jb::if-c [Q <- :wat::WatAST A <- :wat::WatAST E <- :wat::WatAST] -> :wat::WatAST (:jb::tag (:wat::core::quote if) (:jb::list3 Q A E)))

(:wat::core::defn :jb::if? [x <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::tag? (:wat::core::quote if) x)) (:jb::list3? (:jb::untag x)) (:wat::core::quote nil)))

(:wat::core::defn :jb::if_Q [e <- :wat::WatAST] -> :wat::WatAST (:jb::elem1 (:jb::untag e)))

(:wat::core::defn :jb::if_A [e <- :wat::WatAST] -> :wat::WatAST (:jb::elem2 (:jb::untag e)))

(:wat::core::defn :jb::if_E [e <- :wat::WatAST] -> :wat::WatAST (:jb::elem3 (:jb::untag e)))

(:wat::core::defn :jb::app-c [name <- :wat::WatAST args <- :wat::WatAST] -> :wat::WatAST (:jb::cons name args))

(:wat::core::defn :jb::app? [x <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::atom x)) (:wat::core::quote nil) (:wat::core::if (:jb::true? (:jb::quote? x)) (:wat::core::quote nil) (:wat::core::if (:jb::true? (:jb::if? x)) (:wat::core::quote nil) (:wat::core::quote t)))))

(:wat::core::defn :jb::app_name [e <- :wat::WatAST] -> :wat::WatAST (:jb::car e))

(:wat::core::defn :jb::app_args [e <- :wat::WatAST] -> :wat::WatAST (:jb::cdr e))

(:wat::core::defn :jb::var? [x <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::equal x (:wat::core::quote t))) (:wat::core::quote nil) (:wat::core::if (:jb::true? (:jb::equal x (:wat::core::quote nil))) (:wat::core::quote nil) (:wat::core::if (:jb::true? (:jb::natp x)) (:wat::core::quote nil) (:jb::atom x)))))

(:wat::core::defn :jb::defun-c [name <- :wat::WatAST formals <- :wat::WatAST body <- :wat::WatAST] -> :wat::WatAST (:jb::tag (:wat::core::quote defun) (:jb::list3 name formals body)))

(:wat::core::defn :jb::defun? [x <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::tag? (:wat::core::quote defun) x)) (:jb::list3? (:jb::untag x)) (:wat::core::quote nil)))

(:wat::core::defn :jb::defun_name [def <- :wat::WatAST] -> :wat::WatAST (:jb::elem1 (:jb::untag def)))

(:wat::core::defn :jb::defun_formals [def <- :wat::WatAST] -> :wat::WatAST (:jb::elem2 (:jb::untag def)))

(:wat::core::defn :jb::defun_body [def <- :wat::WatAST] -> :wat::WatAST (:jb::elem3 (:jb::untag def)))

(:wat::core::defn :jb::dethm-c [name <- :wat::WatAST formals <- :wat::WatAST body <- :wat::WatAST] -> :wat::WatAST (:jb::tag (:wat::core::quote dethm) (:jb::list3 name formals body)))

(:wat::core::defn :jb::dethm? [x <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::tag? (:wat::core::quote dethm) x)) (:jb::list3? (:jb::untag x)) (:wat::core::quote nil)))

(:wat::core::defn :jb::dethm_name [def <- :wat::WatAST] -> :wat::WatAST (:jb::elem1 (:jb::untag def)))

(:wat::core::defn :jb::dethm_formals [def <- :wat::WatAST] -> :wat::WatAST (:jb::elem2 (:jb::untag def)))

(:wat::core::defn :jb::dethm_body [def <- :wat::WatAST] -> :wat::WatAST (:jb::elem3 (:jb::untag def)))

(:wat::core::defn :jb::if-QAE [e <- :wat::WatAST] -> :wat::WatAST (:jb::list3 (:jb::if_Q e) (:jb::if_A e) (:jb::if_E e)))

(:wat::core::defn :jb::QAE-if [es <- :wat::WatAST] -> :wat::WatAST (:jb::if-c (:jb::elem1 es) (:jb::elem2 es) (:jb::elem3 es)))

(:wat::core::defn :jb::member? [x <- :wat::WatAST ys <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::atom ys)) (:wat::core::quote nil) (:wat::core::if (:jb::true? (:jb::equal x (:jb::car ys))) (:wat::core::quote t) (:jb::member? x (:jb::cdr ys)))))

(:wat::core::defn :jb::rator? [name <- :wat::WatAST] -> :wat::WatAST (:jb::member? name (:wat::core::quote (equal atom car cdr cons natp size + <))))

(:wat::core::defn :jb::rator_formals [rator <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::member? rator (:wat::core::quote (atom car cdr natp size)))) (:wat::core::quote (x)) (:wat::core::if (:jb::true? (:jb::member? rator (:wat::core::quote (equal cons + <)))) (:wat::core::quote (x y)) (:wat::core::quote nil))))

(:wat::core::defn :jb::def_name [def <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::defun? def)) (:jb::defun_name def) (:wat::core::if (:jb::true? (:jb::dethm? def)) (:jb::dethm_name def) def)))

(:wat::core::defn :jb::def_formals [def <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::dethm? def)) (:jb::dethm_formals def) (:wat::core::if (:jb::true? (:jb::defun? def)) (:jb::defun_formals def) (:wat::core::quote ()))))

(:wat::core::defn :jb::if-c-when-necessary [Q <- :wat::WatAST A <- :wat::WatAST E <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::equal A E)) A (:jb::if-c Q A E)))

(:wat::core::defn :jb::conjunction [es <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::atom es)) (:jb::quote-c (:wat::core::quote t)) (:wat::core::if (:jb::true? (:jb::atom (:jb::cdr es))) (:jb::car es) (:jb::if-c (:jb::car es) (:jb::conjunction (:jb::cdr es)) (:jb::quote-c (:wat::core::quote nil))))))

(:wat::core::defn :jb::implication [es <- :wat::WatAST e <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::atom es)) e (:jb::if-c (:jb::car es) (:jb::implication (:jb::cdr es) e) (:jb::quote-c (:wat::core::quote t)))))

(:wat::core::defn :jb::lookup [name <- :wat::WatAST defs <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::atom defs)) name (:wat::core::if (:jb::true? (:jb::equal (:jb::def_name (:jb::car defs)) name)) (:jb::car defs) (:jb::lookup name (:jb::cdr defs)))))

(:wat::core::defn :jb::undefined? [name <- :wat::WatAST defs <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::var? name)) (:jb::equal (:jb::lookup name defs) name) (:wat::core::quote nil)))

(:wat::core::defn :jb::arity? [vars <- :wat::WatAST es <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::atom vars)) (:jb::atom es) (:wat::core::if (:jb::true? (:jb::atom es)) (:wat::core::quote nil) (:jb::arity? (:jb::cdr vars) (:jb::cdr es)))))

(:wat::core::defn :jb::args-arity? [def <- :wat::WatAST args <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::dethm? def)) (:wat::core::quote nil) (:wat::core::if (:jb::true? (:jb::defun? def)) (:jb::arity? (:jb::defun_formals def) args) (:wat::core::if (:jb::true? (:jb::rator? def)) (:jb::arity? (:jb::rator_formals def) args) (:wat::core::quote nil)))))

(:wat::core::defn :jb::app-arity? [defs <- :wat::WatAST app <- :wat::WatAST] -> :wat::WatAST (:jb::args-arity? (:jb::lookup (:jb::app_name app) defs) (:jb::app_args app)))

(:wat::core::defn :jb::bound? [var <- :wat::WatAST vars <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::equal vars (:wat::core::quote any))) (:wat::core::quote t) (:jb::member? var vars)))

(:wat::core::defn :jb::exprs? [defs <- :wat::WatAST vars <- :wat::WatAST es <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::atom es)) (:wat::core::quote t) (:wat::core::if (:jb::true? (:jb::var? (:jb::car es))) (:wat::core::if (:jb::true? (:jb::bound? (:jb::car es) vars)) (:jb::exprs? defs vars (:jb::cdr es)) (:wat::core::quote nil)) (:wat::core::if (:jb::true? (:jb::quote? (:jb::car es))) (:jb::exprs? defs vars (:jb::cdr es)) (:wat::core::if (:jb::true? (:jb::if? (:jb::car es))) (:wat::core::if (:jb::true? (:jb::exprs? defs vars (:jb::if-QAE (:jb::car es)))) (:jb::exprs? defs vars (:jb::cdr es)) (:wat::core::quote nil)) (:wat::core::if (:jb::true? (:jb::app? (:jb::car es))) (:wat::core::if (:jb::true? (:jb::app-arity? defs (:jb::car es))) (:wat::core::if (:jb::true? (:jb::exprs? defs vars (:jb::app_args (:jb::car es)))) (:jb::exprs? defs vars (:jb::cdr es)) (:wat::core::quote nil)) (:wat::core::quote nil)) (:wat::core::quote nil)))))))

(:wat::core::defn :jb::expr? [defs <- :wat::WatAST vars <- :wat::WatAST e <- :wat::WatAST] -> :wat::WatAST (:jb::exprs? defs vars (:jb::list1 e)))

(:wat::core::defn :jb::get-arg-from [n <- :wat::WatAST args <- :wat::WatAST from <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::atom args)) (:wat::core::quote nil) (:wat::core::if (:jb::true? (:jb::equal n from)) (:jb::car args) (:jb::get-arg-from n (:jb::cdr args) (:jb::plus from (:wat::core::quote 1))))))

(:wat::core::defn :jb::get-arg [n <- :wat::WatAST args <- :wat::WatAST] -> :wat::WatAST (:jb::get-arg-from n args (:wat::core::quote 1)))

(:wat::core::defn :jb::set-arg-from [n <- :wat::WatAST args <- :wat::WatAST y <- :wat::WatAST from <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::atom args)) (:wat::core::quote ()) (:wat::core::if (:jb::true? (:jb::equal n from)) (:jb::cons y (:jb::cdr args)) (:jb::cons (:jb::car args) (:jb::set-arg-from n (:jb::cdr args) y (:jb::plus from (:wat::core::quote 1)))))))

(:wat::core::defn :jb::set-arg [n <- :wat::WatAST args <- :wat::WatAST y <- :wat::WatAST] -> :wat::WatAST (:jb::set-arg-from n args y (:wat::core::quote 1)))

(:wat::core::defn :jb::-lt--eq-len-from [n <- :wat::WatAST args <- :wat::WatAST from <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::atom args)) (:wat::core::quote nil) (:wat::core::if (:jb::true? (:jb::equal n from)) (:wat::core::quote t) (:jb::-lt--eq-len-from n (:jb::cdr args) (:jb::plus from (:wat::core::quote 1))))))

(:wat::core::defn :jb::-lt--eq-len [n <- :wat::WatAST args <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::lt (:wat::core::quote 0) n)) (:jb::-lt--eq-len-from n args (:wat::core::quote 1)) (:wat::core::quote nil)))

(:wat::core::defn :jb::subset? [xs <- :wat::WatAST ys <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::atom xs)) (:wat::core::quote t) (:wat::core::if (:jb::true? (:jb::member? (:jb::car xs) ys)) (:jb::subset? (:jb::cdr xs) ys) (:wat::core::quote nil))))

(:wat::core::defn :jb::list-extend [xs <- :wat::WatAST x <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::atom xs)) (:jb::list1 x) (:wat::core::if (:jb::true? (:jb::equal (:jb::car xs) x)) xs (:jb::cons (:jb::car xs) (:jb::list-extend (:jb::cdr xs) x)))))

(:wat::core::defn :jb::list-union [xs <- :wat::WatAST ys <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::atom ys)) xs (:jb::list-union (:jb::list-extend xs (:jb::car ys)) (:jb::cdr ys))))

(:wat::core::defn :jb::formals? [vars <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::atom vars)) (:wat::core::quote t) (:wat::core::if (:jb::true? (:jb::var? (:jb::car vars))) (:wat::core::if (:jb::true? (:jb::member? (:jb::car vars) (:jb::cdr vars))) (:wat::core::quote nil) (:jb::formals? (:jb::cdr vars))) (:wat::core::quote nil))))

(:wat::core::defn :jb::direction? [dir <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::natp dir)) (:wat::core::quote t) (:jb::member? dir (:wat::core::quote (Q A E)))))

(:wat::core::defn :jb::path? [path <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::atom path)) (:wat::core::quote t) (:wat::core::if (:jb::true? (:jb::direction? (:jb::car path))) (:jb::path? (:jb::cdr path)) (:wat::core::quote nil))))

(:wat::core::defn :jb::quoted-exprs? [args <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::atom args)) (:wat::core::quote t) (:wat::core::if (:jb::true? (:jb::quote? (:jb::car args))) (:jb::quoted-exprs? (:jb::cdr args)) (:wat::core::quote nil))))

(:wat::core::defn :jb::step-args? [defs <- :wat::WatAST def <- :wat::WatAST args <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::dethm? def)) (:wat::core::if (:jb::true? (:jb::arity? (:jb::dethm_formals def) args)) (:jb::exprs? defs (:wat::core::quote any) args) (:wat::core::quote nil)) (:wat::core::if (:jb::true? (:jb::defun? def)) (:wat::core::if (:jb::true? (:jb::arity? (:jb::defun_formals def) args)) (:jb::exprs? defs (:wat::core::quote any) args) (:wat::core::quote nil)) (:wat::core::if (:jb::true? (:jb::rator? def)) (:wat::core::if (:jb::true? (:jb::arity? (:jb::rator_formals def) args)) (:jb::quoted-exprs? args) (:wat::core::quote nil)) (:wat::core::quote nil)))))

(:wat::core::defn :jb::step-app? [defs <- :wat::WatAST app <- :wat::WatAST] -> :wat::WatAST (:jb::step-args? defs (:jb::lookup (:jb::app_name app) defs) (:jb::app_args app)))

(:wat::core::defn :jb::step? [defs <- :wat::WatAST step <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::path? (:jb::elem1 step))) (:wat::core::if (:jb::true? (:jb::app? (:jb::elem2 step))) (:jb::step-app? defs (:jb::elem2 step)) (:wat::core::quote nil)) (:wat::core::quote nil)))

(:wat::core::defn :jb::steps? [defs <- :wat::WatAST steps <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::atom steps)) (:wat::core::quote t) (:wat::core::if (:jb::true? (:jb::step? defs (:jb::car steps))) (:jb::steps? defs (:jb::cdr steps)) (:wat::core::quote nil))))

(:wat::core::defn :jb::induction-scheme-for? [def <- :wat::WatAST vars <- :wat::WatAST e <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::defun? def)) (:wat::core::if (:jb::true? (:jb::arity? (:jb::defun_formals def) (:jb::app_args e))) (:wat::core::if (:jb::true? (:jb::formals? (:jb::app_args e))) (:jb::subset? (:jb::app_args e) vars) (:wat::core::quote nil)) (:wat::core::quote nil)) (:wat::core::quote nil)))

(:wat::core::defn :jb::induction-scheme? [defs <- :wat::WatAST vars <- :wat::WatAST e <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::app? e)) (:jb::induction-scheme-for? (:jb::lookup (:jb::app_name e) defs) vars e) (:wat::core::quote nil)))

(:wat::core::defn :jb::seed? [defs <- :wat::WatAST def <- :wat::WatAST seed <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::equal seed (:wat::core::quote nil))) (:wat::core::quote t) (:wat::core::if (:jb::true? (:jb::defun? def)) (:jb::expr? defs (:jb::defun_formals def) seed) (:wat::core::if (:jb::true? (:jb::dethm? def)) (:jb::induction-scheme? defs (:jb::dethm_formals def) seed) (:wat::core::quote nil)))))

(:wat::core::defn :jb::extend-rec [defs <- :wat::WatAST def <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::defun? def)) (:jb::list-extend defs (:jb::defun-c (:jb::defun_name def) (:jb::defun_formals def) (:jb::app-c (:jb::defun_name def) (:jb::defun_formals def)))) defs))

(:wat::core::defn :jb::def-contents? [known-defs <- :wat::WatAST formals <- :wat::WatAST body <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::formals? formals)) (:jb::expr? known-defs formals body) (:wat::core::quote nil)))

(:wat::core::defn :jb::def? [known-defs <- :wat::WatAST def <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::dethm? def)) (:wat::core::if (:jb::true? (:jb::undefined? (:jb::dethm_name def) known-defs)) (:jb::def-contents? known-defs (:jb::dethm_formals def) (:jb::dethm_body def)) (:wat::core::quote nil)) (:wat::core::if (:jb::true? (:jb::defun? def)) (:wat::core::if (:jb::true? (:jb::undefined? (:jb::defun_name def) known-defs)) (:jb::def-contents? (:jb::extend-rec known-defs def) (:jb::defun_formals def) (:jb::defun_body def)) (:wat::core::quote nil)) (:wat::core::quote nil))))

(:wat::core::defn :jb::defs? [known-defs <- :wat::WatAST defs <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::atom defs)) (:wat::core::quote t) (:wat::core::if (:jb::true? (:jb::def? known-defs (:jb::car defs))) (:jb::defs? (:jb::list-extend known-defs (:jb::car defs)) (:jb::cdr defs)) (:wat::core::quote nil))))

(:wat::core::defn :jb::list2-or-more? [pf <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::atom pf)) (:wat::core::quote nil) (:wat::core::if (:jb::true? (:jb::atom (:jb::cdr pf))) (:wat::core::quote nil) (:wat::core::quote t))))

(:wat::core::defn :jb::proof? [defs <- :wat::WatAST pf <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::list2-or-more? pf)) (:wat::core::if (:jb::true? (:jb::def? defs (:jb::elem1 pf))) (:wat::core::if (:jb::true? (:jb::seed? defs (:jb::elem1 pf) (:jb::elem2 pf))) (:jb::steps? (:jb::extend-rec defs (:jb::elem1 pf)) (:jb::cdr (:jb::cdr pf))) (:wat::core::quote nil)) (:wat::core::quote nil)) (:wat::core::quote nil)))

(:wat::core::defn :jb::proofs? [defs <- :wat::WatAST pfs <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::atom pfs)) (:wat::core::quote t) (:wat::core::if (:jb::true? (:jb::proof? defs (:jb::car pfs))) (:jb::proofs? (:jb::list-extend defs (:jb::elem1 (:jb::car pfs))) (:jb::cdr pfs)) (:wat::core::quote nil))))

(:wat::core::defn :jb::sub-var [vars <- :wat::WatAST args <- :wat::WatAST var <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::atom vars)) var (:wat::core::if (:jb::true? (:jb::equal (:jb::car vars) var)) (:jb::car args) (:jb::sub-var (:jb::cdr vars) (:jb::cdr args) var))))

(:wat::core::defn :jb::sub-es [vars <- :wat::WatAST args <- :wat::WatAST es <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::atom es)) (:wat::core::quote ()) (:wat::core::if (:jb::true? (:jb::var? (:jb::car es))) (:jb::cons (:jb::sub-var vars args (:jb::car es)) (:jb::sub-es vars args (:jb::cdr es))) (:wat::core::if (:jb::true? (:jb::quote? (:jb::car es))) (:jb::cons (:jb::car es) (:jb::sub-es vars args (:jb::cdr es))) (:wat::core::if (:jb::true? (:jb::if? (:jb::car es))) (:jb::cons (:jb::QAE-if (:jb::sub-es vars args (:jb::if-QAE (:jb::car es)))) (:jb::sub-es vars args (:jb::cdr es))) (:jb::cons (:jb::app-c (:jb::app_name (:jb::car es)) (:jb::sub-es vars args (:jb::app_args (:jb::car es)))) (:jb::sub-es vars args (:jb::cdr es))))))))

(:wat::core::defn :jb::sub-e [vars <- :wat::WatAST args <- :wat::WatAST e <- :wat::WatAST] -> :wat::WatAST (:jb::elem1 (:jb::sub-es vars args (:jb::list1 e))))

(:wat::core::defn :jb::exprs-recs [f <- :wat::WatAST es <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::atom es)) (:wat::core::quote ()) (:wat::core::if (:jb::true? (:jb::var? (:jb::car es))) (:jb::exprs-recs f (:jb::cdr es)) (:wat::core::if (:jb::true? (:jb::quote? (:jb::car es))) (:jb::exprs-recs f (:jb::cdr es)) (:wat::core::if (:jb::true? (:jb::if? (:jb::car es))) (:jb::list-union (:jb::exprs-recs f (:jb::if-QAE (:jb::car es))) (:jb::exprs-recs f (:jb::cdr es))) (:wat::core::if (:jb::true? (:jb::equal (:jb::app_name (:jb::car es)) f)) (:jb::list-union (:jb::list1 (:jb::car es)) (:jb::list-union (:jb::exprs-recs f (:jb::app_args (:jb::car es))) (:jb::exprs-recs f (:jb::cdr es)))) (:jb::list-union (:jb::exprs-recs f (:jb::app_args (:jb::car es))) (:jb::exprs-recs f (:jb::cdr es)))))))))

(:wat::core::defn :jb::expr-recs [f <- :wat::WatAST e <- :wat::WatAST] -> :wat::WatAST (:jb::exprs-recs f (:jb::list1 e)))

(:wat::core::defn :jb::totality---lt- [meas <- :wat::WatAST formals <- :wat::WatAST app <- :wat::WatAST] -> :wat::WatAST (:jb::app-c (:wat::core::quote <) (:jb::list2 (:jb::sub-e formals (:jb::app_args app) meas) meas)))

(:wat::core::defn :jb::totality--meas [meas <- :wat::WatAST formals <- :wat::WatAST apps <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::atom apps)) (:wat::core::quote ()) (:jb::cons (:jb::totality---lt- meas formals (:jb::car apps)) (:jb::totality--meas meas formals (:jb::cdr apps)))))

(:wat::core::defn :jb::totality--if [meas <- :wat::WatAST f <- :wat::WatAST formals <- :wat::WatAST e <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::if? e)) (:jb::conjunction (:jb::list-extend (:jb::totality--meas meas formals (:jb::expr-recs f (:jb::if_Q e))) (:jb::if-c-when-necessary (:jb::if_Q e) (:jb::totality--if meas f formals (:jb::if_A e)) (:jb::totality--if meas f formals (:jb::if_E e))))) (:jb::conjunction (:jb::totality--meas meas formals (:jb::expr-recs f e)))))

(:wat::core::defn :jb::totality--claim [meas <- :wat::WatAST def <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::equal meas (:wat::core::quote nil))) (:wat::core::if (:jb::true? (:jb::equal (:jb::expr-recs (:jb::defun_name def) (:jb::defun_body def)) (:wat::core::quote ()))) (:jb::quote-c (:wat::core::quote t)) (:jb::quote-c (:wat::core::quote nil))) (:jb::if-c (:jb::app-c (:wat::core::quote natp) (:jb::list1 meas)) (:jb::totality--if meas (:jb::defun_name def) (:jb::defun_formals def) (:jb::defun_body def)) (:jb::quote-c (:wat::core::quote nil)))))

(:wat::core::defn :jb::induction--prems [vars <- :wat::WatAST claim <- :wat::WatAST apps <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::atom apps)) (:wat::core::quote ()) (:jb::cons (:jb::sub-e vars (:jb::app_args (:jb::car apps)) claim) (:jb::induction--prems vars claim (:jb::cdr apps)))))

(:wat::core::defn :jb::induction--if [vars <- :wat::WatAST claim <- :wat::WatAST f <- :wat::WatAST e <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::if? e)) (:jb::implication (:jb::induction--prems vars claim (:jb::expr-recs f (:jb::if_Q e))) (:jb::if-c-when-necessary (:jb::if_Q e) (:jb::induction--if vars claim f (:jb::if_A e)) (:jb::induction--if vars claim f (:jb::if_E e)))) (:jb::implication (:jb::induction--prems vars claim (:jb::expr-recs f e)) claim)))

(:wat::core::defn :jb::induction--defun [vars <- :wat::WatAST claim <- :wat::WatAST def <- :wat::WatAST] -> :wat::WatAST (:jb::induction--if vars claim (:jb::defun_name def) (:jb::sub-e (:jb::defun_formals def) vars (:jb::defun_body def))))

(:wat::core::defn :jb::induction--claim [defs <- :wat::WatAST seed <- :wat::WatAST def <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::equal seed (:wat::core::quote nil))) (:jb::dethm_body def) (:jb::induction--defun (:jb::app_args seed) (:jb::dethm_body def) (:jb::lookup (:jb::app_name seed) defs))))

(:wat::core::defn :jb::find-focus-at-direction [dir <- :wat::WatAST e <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::equal dir (:wat::core::quote Q))) (:jb::if_Q e) (:wat::core::if (:jb::true? (:jb::equal dir (:wat::core::quote A))) (:jb::if_A e) (:wat::core::if (:jb::true? (:jb::equal dir (:wat::core::quote E))) (:jb::if_E e) (:jb::get-arg dir (:jb::app_args e))))))

(:wat::core::defn :jb::rewrite-focus-at-direction [dir <- :wat::WatAST e1 <- :wat::WatAST e2 <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::equal dir (:wat::core::quote Q))) (:jb::if-c e2 (:jb::if_A e1) (:jb::if_E e1)) (:wat::core::if (:jb::true? (:jb::equal dir (:wat::core::quote A))) (:jb::if-c (:jb::if_Q e1) e2 (:jb::if_E e1)) (:wat::core::if (:jb::true? (:jb::equal dir (:wat::core::quote E))) (:jb::if-c (:jb::if_Q e1) (:jb::if_A e1) e2) (:jb::app-c (:jb::app_name e1) (:jb::set-arg dir (:jb::app_args e1) e2))))))

(:wat::core::defn :jb::focus-is-at-direction? [dir <- :wat::WatAST e <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::equal dir (:wat::core::quote Q))) (:jb::if? e) (:wat::core::if (:jb::true? (:jb::equal dir (:wat::core::quote A))) (:jb::if? e) (:wat::core::if (:jb::true? (:jb::equal dir (:wat::core::quote E))) (:jb::if? e) (:wat::core::if (:jb::true? (:jb::app? e)) (:jb::-lt--eq-len dir (:jb::app_args e)) (:wat::core::quote nil))))))

(:wat::core::defn :jb::focus-is-at-path? [path <- :wat::WatAST e <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::atom path)) (:wat::core::quote t) (:wat::core::if (:jb::true? (:jb::focus-is-at-direction? (:jb::car path) e)) (:jb::focus-is-at-path? (:jb::cdr path) (:jb::find-focus-at-direction (:jb::car path) e)) (:wat::core::quote nil))))

(:wat::core::defn :jb::find-focus-at-path [path <- :wat::WatAST e <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::atom path)) e (:jb::find-focus-at-path (:jb::cdr path) (:jb::find-focus-at-direction (:jb::car path) e))))

(:wat::core::defn :jb::rewrite-focus-at-path [path <- :wat::WatAST e1 <- :wat::WatAST e2 <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::atom path)) e2 (:jb::rewrite-focus-at-direction (:jb::car path) e1 (:jb::rewrite-focus-at-path (:jb::cdr path) (:jb::find-focus-at-direction (:jb::car path) e1) e2))))

(:wat::core::defn :jb::prem-A? [prem <- :wat::WatAST path <- :wat::WatAST e <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::atom path)) (:wat::core::quote nil) (:wat::core::if (:jb::true? (:jb::equal (:jb::car path) (:wat::core::quote A))) (:wat::core::if (:jb::true? (:jb::equal (:jb::if_Q e) prem)) (:wat::core::quote t) (:jb::prem-A? prem (:jb::cdr path) (:jb::find-focus-at-direction (:jb::car path) e))) (:jb::prem-A? prem (:jb::cdr path) (:jb::find-focus-at-direction (:jb::car path) e)))))

(:wat::core::defn :jb::prem-E? [prem <- :wat::WatAST path <- :wat::WatAST e <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::atom path)) (:wat::core::quote nil) (:wat::core::if (:jb::true? (:jb::equal (:jb::car path) (:wat::core::quote E))) (:wat::core::if (:jb::true? (:jb::equal (:jb::if_Q e) prem)) (:wat::core::quote t) (:jb::prem-E? prem (:jb::cdr path) (:jb::find-focus-at-direction (:jb::car path) e))) (:jb::prem-E? prem (:jb::cdr path) (:jb::find-focus-at-direction (:jb::car path) e)))))

(:wat::core::defn :jb::follow-prems [path <- :wat::WatAST e <- :wat::WatAST thm <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::if? thm)) (:wat::core::if (:jb::true? (:jb::prem-A? (:jb::if_Q thm) path e)) (:jb::follow-prems path e (:jb::if_A thm)) (:wat::core::if (:jb::true? (:jb::prem-E? (:jb::if_Q thm) path e)) (:jb::follow-prems path e (:jb::if_E thm)) thm)) thm))

(:wat::core::defn :jb::unary-op [rator <- :wat::WatAST rand <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::equal rator (:wat::core::quote atom))) (:jb::atom rand) (:wat::core::if (:jb::true? (:jb::equal rator (:wat::core::quote car))) (:jb::car rand) (:wat::core::if (:jb::true? (:jb::equal rator (:wat::core::quote cdr))) (:jb::cdr rand) (:wat::core::if (:jb::true? (:jb::equal rator (:wat::core::quote natp))) (:jb::natp rand) (:wat::core::if (:jb::true? (:jb::equal rator (:wat::core::quote size))) (:jb::size rand) (:wat::core::quote nil)))))))

(:wat::core::defn :jb::binary-op [rator <- :wat::WatAST rand1 <- :wat::WatAST rand2 <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::equal rator (:wat::core::quote equal))) (:jb::equal rand1 rand2) (:wat::core::if (:jb::true? (:jb::equal rator (:wat::core::quote cons))) (:jb::cons rand1 rand2) (:wat::core::if (:jb::true? (:jb::equal rator (:wat::core::quote +))) (:jb::plus rand1 rand2) (:wat::core::if (:jb::true? (:jb::equal rator (:wat::core::quote <))) (:jb::lt rand1 rand2) (:wat::core::quote nil))))))

(:wat::core::defn :jb::apply-op [rator <- :wat::WatAST rands <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::member? rator (:wat::core::quote (atom car cdr natp size)))) (:jb::unary-op rator (:jb::elem1 rands)) (:wat::core::if (:jb::true? (:jb::member? rator (:wat::core::quote (equal cons + <)))) (:jb::binary-op rator (:jb::elem1 rands) (:jb::elem2 rands)) (:wat::core::quote nil))))

(:wat::core::defn :jb::rands [args <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::atom args)) (:wat::core::quote ()) (:jb::cons (:jb::quote_value (:jb::car args)) (:jb::rands (:jb::cdr args)))))

(:wat::core::defn :jb::eval-op [app <- :wat::WatAST] -> :wat::WatAST (:jb::quote-c (:jb::apply-op (:jb::app_name app) (:jb::rands (:jb::app_args app)))))

(:wat::core::defn :jb::app-of-equal? [e <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::app? e)) (:jb::equal (:jb::app_name e) (:wat::core::quote equal)) (:wat::core::quote nil)))

(:wat::core::defn :jb::equality [focus <- :wat::WatAST a <- :wat::WatAST b <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::equal focus a)) b (:wat::core::if (:jb::true? (:jb::equal focus b)) a focus)))

(:wat::core::defn :jb::equality--equation [focus <- :wat::WatAST concl-inst <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::app-of-equal? concl-inst)) (:jb::equality focus (:jb::elem1 (:jb::app_args concl-inst)) (:jb::elem2 (:jb::app_args concl-inst))) focus))

(:wat::core::defn :jb::equality--path [e <- :wat::WatAST path <- :wat::WatAST thm <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::focus-is-at-path? path e)) (:jb::rewrite-focus-at-path path e (:jb::equality--equation (:jb::find-focus-at-path path e) (:jb::follow-prems path e thm))) e))

(:wat::core::defn :jb::equality--def [claim <- :wat::WatAST path <- :wat::WatAST app <- :wat::WatAST def <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::rator? def)) (:jb::equality--path claim path (:jb::app-c (:wat::core::quote equal) (:jb::list2 app (:jb::eval-op app)))) (:wat::core::if (:jb::true? (:jb::defun? def)) (:jb::equality--path claim path (:jb::sub-e (:jb::defun_formals def) (:jb::app_args app) (:jb::app-c (:wat::core::quote equal) (:jb::list2 (:jb::app-c (:jb::defun_name def) (:jb::defun_formals def)) (:jb::defun_body def))))) (:wat::core::if (:jb::true? (:jb::dethm? def)) (:jb::equality--path claim path (:jb::sub-e (:jb::dethm_formals def) (:jb::app_args app) (:jb::dethm_body def))) claim))))

(:wat::core::defn :jb::rewrite--step [defs <- :wat::WatAST claim <- :wat::WatAST step <- :wat::WatAST] -> :wat::WatAST (:jb::equality--def claim (:jb::elem1 step) (:jb::elem2 step) (:jb::lookup (:jb::app_name (:jb::elem2 step)) defs)))

(:wat::core::defn :jb::rewrite--continue [defs <- :wat::WatAST steps <- :wat::WatAST old <- :wat::WatAST new <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::equal new old)) new (:wat::core::if (:jb::true? (:jb::atom steps)) new (:jb::rewrite--continue defs (:jb::cdr steps) new (:jb::rewrite--step defs new (:jb::car steps))))))

(:wat::core::defn :jb::rewrite--steps [defs <- :wat::WatAST claim <- :wat::WatAST steps <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::atom steps)) claim (:jb::rewrite--continue defs (:jb::cdr steps) claim (:jb::rewrite--step defs claim (:jb::car steps)))))

(:wat::core::defn :jb::rewrite--prove [defs <- :wat::WatAST def <- :wat::WatAST seed <- :wat::WatAST steps <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::defun? def)) (:jb::rewrite--steps defs (:jb::totality--claim seed def) steps) (:wat::core::if (:jb::true? (:jb::dethm? def)) (:jb::rewrite--steps defs (:jb::induction--claim defs seed def) steps) (:jb::quote-c (:wat::core::quote nil)))))

(:wat::core::defn :jb::rewrite--prove-plus-1 [defs <- :wat::WatAST pf <- :wat::WatAST e <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::equal e (:jb::quote-c (:wat::core::quote t)))) (:jb::rewrite--prove defs (:jb::elem1 pf) (:jb::elem2 pf) (:jb::cdr (:jb::cdr pf))) e))

(:wat::core::defn :jb::rewrite--prove-plus- [defs <- :wat::WatAST pfs <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::atom pfs)) (:jb::quote-c (:wat::core::quote t)) (:jb::rewrite--prove-plus-1 defs (:jb::car pfs) (:jb::rewrite--prove-plus- (:jb::list-extend defs (:jb::elem1 (:jb::car pfs))) (:jb::cdr pfs)))))

(:wat::core::defn :jb::rewrite--define [defs <- :wat::WatAST def <- :wat::WatAST seed <- :wat::WatAST steps <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::equal (:jb::rewrite--prove defs def seed steps) (:jb::quote-c (:wat::core::quote t)))) (:jb::list-extend defs def) defs))

(:wat::core::defn :jb::rewrite--define-plus-1 [defs1 <- :wat::WatAST defs2 <- :wat::WatAST pfs <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::equal defs1 defs2)) defs1 (:wat::core::if (:jb::true? (:jb::atom pfs)) defs2 (:jb::rewrite--define-plus-1 defs2 (:jb::rewrite--define defs2 (:jb::elem1 (:jb::car pfs)) (:jb::elem2 (:jb::car pfs)) (:jb::cdr (:jb::cdr (:jb::car pfs)))) (:jb::cdr pfs)))))

(:wat::core::defn :jb::rewrite--define-plus- [defs <- :wat::WatAST pfs <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::atom pfs)) defs (:jb::rewrite--define-plus-1 defs (:jb::rewrite--define defs (:jb::elem1 (:jb::car pfs)) (:jb::elem2 (:jb::car pfs)) (:jb::cdr (:jb::cdr (:jb::car pfs)))) (:jb::cdr pfs))))

(:wat::core::defn :jb::J-Bob--step [defs <- :wat::WatAST e <- :wat::WatAST steps <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::defs? (:wat::core::quote ()) defs)) (:wat::core::if (:jb::true? (:jb::expr? defs (:wat::core::quote any) e)) (:wat::core::if (:jb::true? (:jb::steps? defs steps)) (:jb::rewrite--steps defs e steps) e) e) e))

(:wat::core::defn :jb::J-Bob--prove [defs <- :wat::WatAST pfs <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::defs? (:wat::core::quote ()) defs)) (:wat::core::if (:jb::true? (:jb::proofs? defs pfs)) (:jb::rewrite--prove-plus- defs pfs) (:jb::quote-c (:wat::core::quote nil))) (:jb::quote-c (:wat::core::quote nil))))

(:wat::core::defn :jb::J-Bob--define [defs <- :wat::WatAST pfs <- :wat::WatAST] -> :wat::WatAST (:wat::core::if (:jb::true? (:jb::defs? (:wat::core::quote ()) defs)) (:wat::core::if (:jb::true? (:jb::proofs? defs pfs)) (:jb::rewrite--define-plus- defs pfs) defs) defs))

(:wat::core::def :jb::axioms (:wat::core::quote ((dethm atom/cons (x y) (equal (atom (cons x y)) (quote nil))) (dethm car/cons (x y) (equal (car (cons x y)) x)) (dethm cdr/cons (x y) (equal (cdr (cons x y)) y)) (dethm equal-same (x) (equal (equal x x) (quote t))) (dethm equal-swap (x y) (equal (equal x y) (equal y x))) (dethm if-same (x y) (equal (if x y y) y)) (dethm if-true (x y) (equal (if (quote t) x y) x)) (dethm if-false (x y) (equal (if (quote nil) x y) y)) (dethm if-nest-E (x y z) (if x (quote t) (equal (if x y z) z))) (dethm if-nest-A (x y z) (if x (equal (if x y z) y) (quote t))) (dethm cons/car+cdr (x) (if (atom x) (quote t) (equal (cons (car x) (cdr x)) x))) (dethm equal-if (x y) (if (equal x y) (equal x y) (quote t))) (dethm natp/size (x) (equal (natp (size x)) (quote t))) (dethm size/car (x) (if (atom x) (quote t) (equal (< (size (car x)) (size x)) (quote t)))) (dethm size/cdr (x) (if (atom x) (quote t) (equal (< (size (cdr x)) (size x)) (quote t)))) (dethm associate-+ (a b c) (equal (+ (+ a b) c) (+ a (+ b c)))) (dethm commute-+ (x y) (equal (+ x y) (+ y x))) (dethm natp/+ (x y) (if (natp x) (if (natp y) (equal (natp (+ x y)) (quote t)) (quote t)) (quote t))) (dethm positives-+ (x y) (if (< (quote 0) x) (if (< (quote 0) y) (equal (< (quote 0) (+ x y)) (quote t)) (quote t)) (quote t))) (dethm common-addends-< (x y z) (equal (< (+ x z) (+ y z)) (< x y))) (dethm identity-+ (x) (if (natp x) (equal (+ (quote 0) x) x) (quote t))))))

(:wat::core::def :jb::prelude (:jb::J-Bob--define :jb::axioms (:wat::core::quote (((defun list-induction (x) (if (atom x) (quote ()) (cons (car x) (list-induction (cdr x))))) (size x) ((A E) (size/cdr x)) ((A) (if-same (atom x) (quote t))) ((Q) (natp/size x)) (() (if-true (quote t) (quote nil)))) ((defun star-induction (x) (if (atom x) x (cons (star-induction (car x)) (star-induction (cdr x))))) (size x) ((A E A) (size/cdr x)) ((A E Q) (size/car x)) ((A E) (if-true (quote t) (quote nil))) ((A) (if-same (atom x) (quote t))) ((Q) (natp/size x)) (() (if-true (quote t) (quote nil))))))))

