;; GENERATED by tools/jbob2wat.wat from vendor/j-bob/little-prover.scm (BSD 2-Clause, Friedman and Eastlund). Do not edit by hand.

(:wat::core::def :jb::chapter1_example1 (:jb::J-Bob--step :jb::prelude (:wat::core::quote (car (cons (quote ham) (quote (eggs))))) (:wat::core::quote (((1) (cons (quote ham) (quote (eggs)))) (() (car (quote (ham eggs))))))))

(:wat::core::def :jb::chapter1_example2 (:jb::J-Bob--step :jb::prelude (:wat::core::quote (atom (quote ()))) (:wat::core::quote ((() (atom (quote ())))))))

(:wat::core::def :jb::chapter1_example3 (:jb::J-Bob--step :jb::prelude (:wat::core::quote (atom (cons (quote ham) (quote (eggs))))) (:wat::core::quote (((1) (cons (quote ham) (quote (eggs)))) (() (atom (quote (ham eggs))))))))

(:wat::core::def :jb::chapter1_example4 (:jb::J-Bob--step :jb::prelude (:wat::core::quote (atom (cons a b))) (:wat::core::quote ((() (atom/cons a b))))))

(:wat::core::def :jb::chapter1_example5 (:jb::J-Bob--step :jb::prelude (:wat::core::quote (equal (quote flapjack) (atom (cons a b)))) (:wat::core::quote (((2) (atom/cons a b)) (() (equal (quote flapjack) (quote nil)))))))

(:wat::core::def :jb::chapter1_example6 (:jb::J-Bob--step :jb::prelude (:wat::core::quote (atom (cdr (cons (car (cons p q)) (quote ()))))) (:wat::core::quote (((1 1 1) (car/cons p q)) ((1) (cdr/cons p (quote ()))) (() (atom (quote ())))))))

(:wat::core::def :jb::chapter1_example7 (:jb::J-Bob--step :jb::prelude (:wat::core::quote (atom (cdr (cons (car (cons p q)) (quote ()))))) (:wat::core::quote (((1) (cdr/cons (car (cons p q)) (quote ()))) (() (atom (quote ())))))))

(:wat::core::def :jb::chapter1_example8 (:jb::J-Bob--step :jb::prelude (:wat::core::quote (car (cons (equal (cons x y) (cons x y)) (quote (and crumpets))))) (:wat::core::quote (((1 1) (equal-same (cons x y))) ((1) (cons (quote t) (quote (and crumpets)))) (() (car (quote (t and crumpets))))))))

(:wat::core::def :jb::chapter1_example9 (:jb::J-Bob--step :jb::prelude (:wat::core::quote (equal (cons x y) (cons (quote bagels) (quote (and lox))))) (:wat::core::quote ((() (equal-swap (cons x y) (cons (quote bagels) (quote (and lox)))))))))

(:wat::core::def :jb::chapter1_example10 (:jb::J-Bob--step :jb::prelude (:wat::core::quote (cons y (equal (car (cons (cdr x) (car y))) (equal (atom x) (quote nil))))) (:wat::core::quote (((2 1) (car/cons (cdr x) (car y)))))))

(:wat::core::def :jb::chapter1_example11 (:jb::J-Bob--step :jb::prelude (:wat::core::quote (cons y (equal (car (cons (cdr x) (car y))) (equal (atom x) (quote nil))))) (:wat::core::quote (((2 1) (car/cons (car (cons (cdr x) (car y))) (quote (oats)))) ((2 2 2) (atom/cons (atom (cdr (cons a b))) (equal (cons a b) c))) ((2 2 2 1 1 1) (cdr/cons a b)) ((2 2 2 1 2) (equal-swap (cons a b) c))))))

(:wat::core::def :jb::chapter1_example12 (:jb::J-Bob--step :jb::prelude (:wat::core::quote (atom (car (cons (car a) (cdr b))))) (:wat::core::quote (((1) (car/cons (car a) (cdr b)))))))

