;; GENERATED by tools/jbob2wat.wat from vendor/j-bob/little-prover.scm (BSD 2-Clause, Friedman and Eastlund). Do not edit by hand.

(:wat::core::def :jb::defun_pair (:jb::J-Bob--define :jb::prelude (:wat::core::quote (((defun pair (x y) (cons x (cons y (quote ())))) nil)))))

(:wat::core::def :jb::defun_first-of (:jb::J-Bob--define :jb::defun_pair (:wat::core::quote (((defun first-of (x) (car x)) nil)))))

(:wat::core::def :jb::defun_second-of (:jb::J-Bob--define :jb::defun_first-of (:wat::core::quote (((defun second-of (x) (car (cdr x))) nil)))))

(:wat::core::def :jb::dethm_first-of-pair (:jb::J-Bob--define :jb::defun_second-of (:wat::core::quote (((dethm first-of-pair (a b) (equal (first-of (pair a b)) a)) nil ((1 1) (pair a b)) ((1) (first-of (cons a (cons b (quote ()))))) ((1) (car/cons a (cons b (quote ())))) (() (equal-same a)))))))

(:wat::core::def :jb::dethm_second-of-pair (:jb::J-Bob--define :jb::dethm_first-of-pair (:wat::core::quote (((dethm second-of-pair (a b) (equal (second-of (pair a b)) b)) nil ((1) (second-of (pair a b))) ((1 1 1) (pair a b)) ((1 1) (cdr/cons a (cons b (quote ())))) ((1) (car/cons b (quote ()))) (() (equal-same b)))))))

(:wat::core::def :jb::defun_in-pair? (:jb::J-Bob--define :jb::dethm_second-of-pair (:wat::core::quote (((defun in-pair? (xs) (if (equal (first-of xs) (quote ?)) (quote t) (equal (second-of xs) (quote ?)))) nil)))))

(:wat::core::def :jb::dethm_in-first-of-pair (:jb::J-Bob--define :jb::defun_in-pair? (:wat::core::quote (((dethm in-first-of-pair (b) (equal (in-pair? (pair (quote ?) b)) (quote t))) nil ((1 1) (pair (quote ?) b)) ((1) (in-pair? (cons (quote ?) (cons b (quote ()))))) ((1 Q 1) (first-of (cons (quote ?) (cons b (quote ()))))) ((1 Q 1) (car/cons (quote ?) (cons b (quote ())))) ((1 Q) (equal-same (quote ?))) ((1) (if-true (quote t) (equal (second-of (cons (quote ?) (cons b (quote ())))) (quote ?)))) (() (equal-same (quote t))))))))

(:wat::core::def :jb::dethm_in-second-of-pair (:jb::J-Bob--define :jb::dethm_in-first-of-pair (:wat::core::quote (((dethm in-second-of-pair (a) (equal (in-pair? (pair a (quote ?))) (quote t))) nil ((1 1) (pair a (quote ?))) ((1) (in-pair? (cons a (cons (quote ?) (quote ()))))) ((1 Q 1) (first-of (cons a (cons (quote ?) (quote ()))))) ((1 Q 1) (car/cons a (cons (quote ?) (quote ())))) ((1 E 1) (second-of (cons a (cons (quote ?) (quote ()))))) ((1 E 1 1) (cdr/cons a (cons (quote ?) (quote ())))) ((1 E 1) (car/cons (quote ?) (quote ()))) ((1 E) (equal-same (quote ?))) ((1) (if-same (equal a (quote ?)) (quote t))) (() (equal-same (quote t))))))))

