;; GENERATED by tools/jbob2wat.wat from vendor/j-bob/little-prover.scm (BSD 2-Clause, Friedman and Eastlund). Do not edit by hand.

(:wat::core::def :jb::defun_list0? (:jb::J-Bob--define :jb::dethm_in-second-of-pair (:wat::core::quote (((defun list0? (x) (equal x (quote ()))) nil)))))

(:wat::core::def :jb::defun_list1? (:jb::J-Bob--define :jb::defun_list0? (:wat::core::quote (((defun list1? (x) (if (atom x) (quote nil) (list0? (cdr x)))) nil)))))

(:wat::core::def :jb::defun_list2? (:jb::J-Bob--define :jb::defun_list1? (:wat::core::quote (((defun list2? (x) (if (atom x) (quote nil) (list1? (cdr x)))) nil)))))

(:wat::core::def :jb::dethm_contradiction (:jb::J-Bob--prove (:jb::list-extend :jb::prelude (:wat::core::quote (defun partial (x) (if (partial x) (quote nil) (quote t))))) (:wat::core::quote (((dethm contradiction () (quote nil)) nil (() (if-same (partial x) (quote nil))) ((A) (if-nest-A (partial x) (quote nil) (quote t))) ((E) (if-nest-E (partial x) (quote t) (quote nil))) ((A Q) (partial x)) ((E Q) (partial x)) ((A Q) (if-nest-A (partial x) (quote nil) (quote t))) ((E Q) (if-nest-E (partial x) (quote nil) (quote t))) ((A) (if-false (quote nil) (quote t))) ((E) (if-true (quote t) (quote nil))) (() (if-same (partial x) (quote t))))))))

(:wat::core::def :jb::defun_list? (:jb::J-Bob--define :jb::defun_list2? (:wat::core::quote (((defun list? (x) (if (atom x) (equal x (quote ())) (list? (cdr x)))) (size x) ((Q) (natp/size x)) (() (if-true (if (atom x) (quote t) (< (size (cdr x)) (size x))) (quote nil))) ((E) (size/cdr x)) (() (if-same (atom x) (quote t))))))))

(:wat::core::def :jb::defun_sub (:jb::J-Bob--define :jb::defun_list? (:wat::core::quote (((defun sub (x y) (if (atom y) (if (equal y (quote ?)) x y) (cons (sub x (car y)) (sub x (cdr y))))) (size y) ((Q) (natp/size y)) (() (if-true (if (atom y) (quote t) (if (< (size (car y)) (size y)) (< (size (cdr y)) (size y)) (quote nil))) (quote nil))) ((E Q) (size/car y)) ((E A) (size/cdr y)) ((E) (if-true (quote t) (quote nil))) (() (if-same (atom y) (quote t))))))))

