;; probes/grep/written-is-exact.wat: is wat-grep's `Written` predicate exact, at corpus scale?
;;
;; `Named` says WHAT a node is called; `Written` says AND IT IS SPELLED HERE. The distinction
;; exists because the reader synthesizes nodes: `~x` reads as a node NAMED
;; `:wat::core::unquote` whose span covers the token `~x`, so a REWRITING rule that joined
;; `Named` to `Span` would overwrite `~x` with the text `:wat::core::unquote`. wat-rs measured
;; that as 50 real corruption sites before it was fixed, one of them a test asserting two chars
;; unequal, which would have been INVERTED rather than broken.
;;
;; The guard, from grep.wat:80-85:
;;
;;   `ast-name` returns verbatim token TEXT, so for a single-line named node
;;   `end-col - col == length(name)` iff the name is actually spelled at that span;
;;   NOT A HEURISTIC.
;;
;; and the audit note that drove it claims it is exact on its sample: "empirically 172/172
;; genuine matches satisfied it and 50/50 phantoms violated it; now it is grounded in the
;; mechanism as well as the sample."
;;
;; 222 nodes is a sample. This repository is 533 files and 136,697 nodes, of which 85,347 are
;; Named and 79,749 Written -- so 5,598 nodes carry a name that the predicate says is not
;; spelled at its span. If the predicate is exact, EVERY ONE of those 5,598 must be a
;; reader-synthesized name: unquote, quasiquote, unquote-splicing, char/of, holon/literal and
;; nothing else. One ordinary name in that set means the predicate over-rejects, and a rewriting
;; rule would silently skip real sites -- the quiet direction of the same bug.
;;
;; This prints one UNWRITTEN line per such node so the set can be tallied outside wat.
;;
;; Run from the repository root: wat probes/grep/written-is-exact.wat

(:wat::core::typealias :we::Paths (:wat::core::Vector :- [:wat::core::String]))
(:wat::core::typealias :we::IdSet (:wat::core::PersistentMap :- [:wat::core::i64 :wat::core::bool]))

(:wat::core::defn :we::written-ids [f <- :wat::grep::Facts] -> :we::IdSet
  (:wat::core::foldl
    (:wat::core::fn [m <- :we::IdSet w <- :wat::grep::Written] -> :we::IdSet
      (:wat::map::assoc m (:wat::grep::Written/id w) true))
    (:wat::core::PersistentMap :- [:wat::core::i64 :wat::core::bool])
    (:wat::grep::Facts/written f)))

(:wat::core::typealias :we::KindMap (:wat::core::PersistentMap :- [:wat::core::i64 :wat::core::String]))

(:wat::core::defn :we::kind->s [k <- :wat::grep::NodeKind] -> :wat::core::String
  (:wat::core::match k
    [:wat::grep::NodeKind.IntLit {} "IntLit"]
    [:wat::grep::NodeKind.FloatLit {} "FloatLit"]
    [:wat::grep::NodeKind.RationalLit {} "RationalLit"]
    [:wat::grep::NodeKind.BigIntLit {} "BigIntLit"]
    [:wat::grep::NodeKind.CharLit {} "CharLit"]
    [:wat::grep::NodeKind.BoolLit {} "BoolLit"]
    [:wat::grep::NodeKind.StringLit {} "StringLit"]
    [:wat::grep::NodeKind.NilLit {} "NilLit"]
    [:wat::grep::NodeKind.Keyword {} "Keyword"]
    [:wat::grep::NodeKind.Symbol {} "Symbol"]
    [:wat::grep::NodeKind.List {} "List"]
    [:wat::grep::NodeKind.Vector {} "Vector"]
    [:wat::grep::NodeKind.Set {} "Set"]
    [:wat::grep::NodeKind.Map {} "Map"]))

(:wat::core::defn :we::kinds [f <- :wat::grep::Facts] -> :we::KindMap
  (:wat::core::foldl
    (:wat::core::fn [m <- :we::KindMap n <- :wat::grep::Node] -> :we::KindMap
      (:wat::map::assoc m (:wat::grep::Node/id n) (:we::kind->s (:wat::grep::Node/kind n))))
    (:wat::core::PersistentMap :- [:wat::core::i64 :wat::core::String])
    (:wat::grep::Facts/nodes f)))

(:wat::core::defn :we::kind-at [m <- :we::KindMap id <- :wat::core::i64] -> :wat::core::String
  (:wat::core::match (:wat::map::get m id)
    [:wat::core::Option.Some {:value v} v]
    [:wat::core::Option.None {} "?"]))

;; How many Written facts are themselves string literals? A StringLit's span covers its quotes,
;; so end-col - col == length(name) + 2 always, and the predicate can never admit one. If this
;; is 0 across the corpus, that is proved rather than argued.
(:wat::core::defn :we::written-strings [f <- :wat::grep::Facts km <- :we::KindMap] -> :wat::core::i64
  (:wat::core::foldl
    (:wat::core::fn [a <- :wat::core::i64 w <- :wat::grep::Written] -> :wat::core::i64
      (:wat::core::if (:wat::core::= (:we::kind-at km (:wat::grep::Written/id w)) "StringLit")
        (:wat::core::+ a 1) a))
    0 (:wat::grep::Facts/written f)))

(:wat::core::defn :we::in? [m <- :we::IdSet id <- :wat::core::i64] -> :wat::core::bool
  (:wat::core::match (:wat::map::get m id)
    [:wat::core::Option.Some {:value v} v]
    [:wat::core::Option.None {} false]))

;; Print the name of every Named node that carries no Written fact, and return how many.
(:wat::core::defn :we::report [path <- :wat::core::String] -> :wat::core::i64
  (:wat::core::let [facts (:wat::grep::facts-of path (:wat::io::read-file path))
                    wids  (:we::written-ids facts)
                    kmap  (:we::kinds facts)
                    ;; foldl, not filterv: :wat::core::filterv is the ONE core sequence verb
                    ;; that has no PersistentVector clause, and every vector in grep::Facts is a
                    ;; PersistentVector. See F-080.
                    miss  (:wat::core::foldl
                            (:wat::core::fn [a <- :wat::core::i64 n <- :wat::grep::Named] -> :wat::core::i64
                              (:wat::core::if (:we::in? wids (:wat::grep::Named/id n))
                                a
                                (:wat::core::do
                                  (:wat::kernel::println
                                    (:wat::string::concat "UNWRITTEN "
                                      (:wat::string::concat (:we::kind-at kmap (:wat::grep::Named/id n))
                                        (:wat::string::concat " " (:wat::grep::Named/name n)))))
                                  (:wat::core::+ a 1))))
                            0
                            (:wat::grep::Facts/named facts))]
    (:wat::core::do
      (:wat::kernel::println (:wat::string::concat "WRITTEN-STRINGLITS "
        (:wat::i64::to-string (:we::written-strings facts kmap))))
      (:wat::kernel::println (:wat::string::concat "TOTALS "
        (:wat::string::concat (:wat::i64::to-string (:wat::core::length (:wat::grep::Facts/nodes facts)))
          (:wat::string::concat " "
            (:wat::string::concat (:wat::i64::to-string (:wat::core::length (:wat::grep::Facts/named facts)))
              (:wat::string::concat " "
                (:wat::i64::to-string (:wat::core::length (:wat::grep::Facts/written facts)))))))))
      miss)))
(:wat::core::defn :we::paths [] -> :we::Paths
  (:wat::core::Vector :- [:wat::core::String]
    "aoc/day01-sonar.wat"
    "aoc/day02-smoke.wat"
    "aoc/day03-words.wat"
    "aoc/day04-binary.wat"
    "aoc/day05-paths.wat"
    "aoc/lib/check.wat"
    "books/little-java/ch01-modern-toys.wat"
    "books/little-java/ch02-methods-to-our-madness.wat"
    "books/little-java/ch03-whats-new.wat"
    "books/little-java/ch04-come-to-our-carousel.wat"
    "books/little-java/ch05-objects-are-people-too.wat"
    "books/little-java/ch06-boring-protocols.wat"
    "books/little-java/ch07-oh-my.wat"
    "books/little-java/ch08-like-father-like-son.wat"
    "books/little-java/ch09-be-a-good-visitor.wat"
    "books/little-java/ch10-the-state-of-things-to-come.wat"
    "books/little-java/lib/check.wat"
    "books/little-learner/ch01-the-lines-sleep-tonight.wat"
    "books/little-learner/ch02-the-more-we-learn-the-tenser-we-become.wat"
    "books/little-learner/ch02i-the-more-we-extend-the-less-tensor-we-get.wat"
    "books/little-learner/ch03-running-down-a-slippery-slope.wat"
    "books/little-learner/ch04-slip-slidin-away.wat"
    "books/little-learner/ch04i-too-many-toys-make-us-hyperactive.wat"
    "books/little-learner/ch05-target-practice.wat"
    "books/little-learner/ch05i-the-shape-of-things-to-come.wat"
    "books/little-learner/ch06-an-apple-a-day.wat"
    "books/little-learner/ch07-the-crazy-ates.wat"
    "books/little-learner/ch08-the-nearer-your-destination-the-slower-you-become.wat"
    "books/little-learner/ch08i-smooth-operator.wat"
    "books/little-learner/ch09-be-adamant.wat"
    "books/little-learner/ch09i-extensio-magnifico.wat"
    "books/little-learner/ch10-doing-the-neuron-dance.wat"
    "books/little-learner/ch11-in-love-with-the-shape-of-relu.wat"
    "books/little-learner/ch12-rock-around-the-block.wat"
    "books/little-learner/ch13-an-eye-for-an-iris.wat"
    "books/little-learner/ch13i-how-the-model-trains.wat"
    "books/little-learner/ch13ii-are-your-signals-crossed.wat"
    "books/little-learner/ch14-its-really-not-that-convoluted.wat"
    "books/little-learner/ch15-morse.wat"
    "books/little-learner/lib/check.wat"
    "books/little-learner/lib/malt.wat"
    "books/little-learner/lib/sampling.wat"
    "books/little-mler/ch01-building-blocks.wat"
    "books/little-mler/ch02-matchmaker.wat"
    "books/little-mler/ch03-cons-is-still-magnificent.wat"
    "books/little-mler/ch04-look-to-the-stars.wat"
    "books/little-mler/ch05-couples-are-magnificent-too.wat"
    "books/little-mler/ch06-oh-my-its-full-of-stars.wat"
    "books/little-mler/ch07-functions-are-people-too.wat"
    "books/little-mler/ch08-bows-and-arrows.wat"
    "books/little-mler/ch09-oh-no.wat"
    "books/little-mler/ch10-building-on-blocks.wat"
    "books/little-mler/lib/ch01-building-blocks.wat"
    "books/little-mler/lib/ch02-matchmaker.wat"
    "books/little-mler/lib/ch03-cons-is-still-magnificent.wat"
    "books/little-mler/lib/ch04-look-to-the-stars.wat"
    "books/little-mler/lib/ch05-couples-are-magnificent-too.wat"
    "books/little-mler/lib/ch06-oh-my-its-full-of-stars.wat"
    "books/little-mler/lib/ch07-functions-are-people-too.wat"
    "books/little-mler/lib/ch08-bows-and-arrows.wat"
    "books/little-mler/lib/ch09-oh-no.wat"
    "books/little-mler/lib/ch10-building-on-blocks.wat"
    "books/little-prover/ch01-transcript.wat"
    "books/little-prover/ch02-transcript.wat"
    "books/little-prover/ch03-transcript.wat"
    "books/little-prover/ch04-transcript.wat"
    "books/little-prover/ch05-transcript.wat"
    "books/little-prover/ch06-transcript.wat"
    "books/little-prover/ch07-transcript.wat"
    "books/little-prover/ch08-transcript.wat"
    "books/little-prover/ch09-transcript.wat"
    "books/little-prover/lib/j-bob-lang.wat"
    "books/little-prover/lib/j-bob.wat"
    "books/little-prover/lib/transcript-ch01.wat"
    "books/little-prover/lib/transcript-ch02.wat"
    "books/little-prover/lib/transcript-ch03.wat"
    "books/little-prover/lib/transcript-ch04.wat"
    "books/little-prover/lib/transcript-ch05.wat"
    "books/little-prover/lib/transcript-ch06.wat"
    "books/little-prover/lib/transcript-ch07.wat"
    "books/little-prover/lib/transcript-ch08.wat"
    "books/little-prover/lib/transcript-ch09.wat"
    "books/little-schemer/ch01-toys.wat"
    "books/little-schemer/ch02-do-it-again.wat"
    "books/little-schemer/ch03-cons-the-magnificent.wat"
    "books/little-schemer/ch04-numbers-games.wat"
    "books/little-schemer/ch05-full-of-stars.wat"
    "books/little-schemer/ch06-shadows.wat"
    "books/little-schemer/ch07-friends-and-relations.wat"
    "books/little-schemer/ch08-lambda-the-ultimate.wat"
    "books/little-schemer/ch09-and-again.wat"
    "books/little-schemer/ch10-value.wat"
    "books/little-schemer/lib/ch01-toys.wat"
    "books/little-schemer/lib/ch02-do-it-again.wat"
    "books/little-schemer/lib/ch03-cons-the-magnificent.wat"
    "books/little-schemer/lib/ch04-numbers-games.wat"
    "books/little-schemer/lib/ch05-full-of-stars.wat"
    "books/little-schemer/lib/ch06-shadows.wat"
    "books/little-schemer/lib/ch07-friends-and-relations.wat"
    "books/little-schemer/lib/ch08-lambda-the-ultimate.wat"
    "books/little-schemer/lib/ch09-and-again.wat"
    "books/little-schemer/lib/ch10-value.wat"
    "books/little-typer/ch01-the-more-things-change.wat"
    "books/little-typer/ch02-doin-what-comes-naturally.wat"
    "books/little-typer/ch03-eliminate-all-natural-numbers.wat"
    "books/little-typer/ch04-easy-as-pie.wat"
    "books/little-typer/ch05-lists-lists-and-more-lists.wat"
    "books/little-typer/ch06-precisely-how-many.wat"
    "books/little-typer/ch07-it-all-depends-on-the-motive.wat"
    "books/little-typer/ch08-pick-a-number-any-number.wat"
    "books/little-typer/ch09-double-your-money-get-twice-as-much.wat"
    "books/little-typer/ch10-it-also-depends-on-the-list.wat"
    "books/little-typer/ch11-all-lists-are-created-equal.wat"
    "books/little-typer/ch12-even-numbers-can-be-odd.wat"
    "books/little-typer/ch13-even-haf-a-bakers-dozen.wat"
    "books/little-typer/ch14-theres-safety-in-numbers.wat"
    "books/little-typer/ch15-imagine-that.wat"
    "books/little-typer/ch16-if-its-all-the-same-to-you.wat"
    "books/little-typer/lib/pie.wat"
    "books/reasoned-schemer/ch01-playthings.wat"
    "books/reasoned-schemer/ch02-old-toys.wat"
    "books/reasoned-schemer/ch03-old-friends.wat"
    "books/reasoned-schemer/ch04-double-your-fun.wat"
    "books/reasoned-schemer/ch05-members-only.wat"
    "books/reasoned-schemer/ch06-the-fun-never-ends.wat"
    "books/reasoned-schemer/ch07-a-bit-too-much.wat"
    "books/reasoned-schemer/ch08-just-a-bit-more.wat"
    "books/reasoned-schemer/ch09-thin-ice.wat"
    "books/reasoned-schemer/ch10-under-the-hood.wat"
    "books/reasoned-schemer/lib/ch01-playthings.wat"
    "books/reasoned-schemer/lib/ch02-old-toys.wat"
    "books/reasoned-schemer/lib/ch03-old-friends.wat"
    "books/reasoned-schemer/lib/ch04-double-your-fun.wat"
    "books/reasoned-schemer/lib/ch05-members-only.wat"
    "books/reasoned-schemer/lib/ch06-the-fun-never-ends.wat"
    "books/reasoned-schemer/lib/ch07-a-bit-too-much.wat"
    "books/reasoned-schemer/lib/ch08-just-a-bit-more.wat"
    "books/reasoned-schemer/lib/ch09-thin-ice.wat"
    "books/reasoned-schemer/lib/ch10-under-the-hood.wat"
    "books/seasoned-schemer/ch11-welcome-back.wat"
    "books/seasoned-schemer/ch12-take-cover.wat"
    "books/seasoned-schemer/ch13-hop-skip-jump.wat"
    "books/seasoned-schemer/ch14-let-there-be-names.wat"
    "books/seasoned-schemer/ch15-men-and-boys.wat"
    "books/seasoned-schemer/ch16-ready-set-bang.wat"
    "books/seasoned-schemer/ch17-we-change.wat"
    "books/seasoned-schemer/ch18-the-same.wat"
    "books/seasoned-schemer/ch19-absconding.wat"
    "books/seasoned-schemer/ch20-whats-in-store.wat"
    "books/seasoned-schemer/lib/arena.wat"
    "books/seasoned-schemer/lib/cell.wat"
    "books/seasoned-schemer/lib/ch11-welcome-back.wat"
    "books/seasoned-schemer/lib/ch12-take-cover.wat"
    "books/seasoned-schemer/lib/ch13-hop-skip-jump.wat"
    "books/seasoned-schemer/lib/ch14-let-there-be-names.wat"
    "books/seasoned-schemer/lib/ch15-men-and-boys.wat"
    "books/seasoned-schemer/lib/ch16-ready-set-bang.wat"
    "books/seasoned-schemer/lib/ch17-we-change.wat"
    "books/seasoned-schemer/lib/ch18-the-same.wat"
    "books/seasoned-schemer/lib/ch19-absconding.wat"
    "books/seasoned-schemer/lib/ch20-whats-in-store.wat"
    "books/seasoned-schemer/lib/counter.wat"
    "euler/lib/check.wat"
    "euler/p16-p20-p25-digits.wat"
    "euler/p22-names-scores.wat"
    "koans/idiom/01-equalities.wat"
    "koans/idiom/02-strings.wat"
    "koans/idiom/03-lists.wat"
    "koans/idiom/04-vectors.wat"
    "koans/idiom/05-sets.wat"
    "koans/idiom/06-maps.wat"
    "koans/idiom/07-functions.wat"
    "koans/idiom/08-conditionals.wat"
    "koans/idiom/09-higher-order-functions.wat"
    "koans/idiom/10-runtime-polymorphism.wat"
    "koans/idiom/11-lazy-sequences.wat"
    "koans/idiom/12-sequence-comprehensions.wat"
    "koans/idiom/13-creating-functions.wat"
    "koans/idiom/14-recursion.wat"
    "koans/idiom/15-destructuring.wat"
    "koans/idiom/16-refs.wat"
    "koans/idiom/17-atoms.wat"
    "koans/idiom/18-quote.wat"
    "koans/idiom/19-datatypes.wat"
    "koans/idiom/20-java-interop.wat"
    "koans/idiom/21-partition.wat"
    "koans/idiom/22-group-by.wat"
    "koans/idiom/23-meta.wat"
    "koans/idiom/24-macros.wat"
    "koans/idiom/25-threading-macros.wat"
    "koans/idiom/26-transducers.wat"
    "koans/idiom/27-multimethods.wat"
    "paip/ch11-unification.wat"
    "paip/ch12-prolog.wat"
    "paip/lib/check.wat"
    "paip/lib/prolog.wat"
    "paip/lib/unify.wat"
    "probes/annoy/argtype-user-fn-clj.wat"
    "probes/annoy/argtype-user-fn-kw.wat"
    "probes/annoy/arity-core-fn-kw.wat"
    "probes/annoy/arity-core-fn.wat"
    "probes/annoy/arity-local-lambda-clj.wat"
    "probes/annoy/arity-local-lambda-cljlet-kwfn.wat"
    "probes/annoy/arity-local-lambda-kwlet-cljfn.wat"
    "probes/annoy/arity-local-lambda-kwlet-kwfn.wat"
    "probes/annoy/arity-user-fn-kw.wat"
    "probes/annoy/arity-user-fn.wat"
    "probes/annoy/assert-eq-vector-fail.wat"
    "probes/annoy/assert-eq-watast-fail.wat"
    "probes/annoy/clj-defn-bad-return.wat"
    "probes/annoy/clj-defn-body-kwcall.wat"
    "probes/annoy/cond-flat.wat"
    "probes/annoy/discard-inside-quote.wat"
    "probes/annoy/discard-reader.wat"
    "probes/annoy/docstring-defn-uncalled.wat"
    "probes/annoy/docstring-defn.wat"
    "probes/annoy/double-load.wat"
    "probes/annoy/if-let.wat"
    "probes/annoy/keyword-as-fn.wat"
    "probes/annoy/kwcall-to-clj-defn.wat"
    "probes/annoy/load-clj-missing.wat"
    "probes/annoy/load-clj.wat"
    "probes/annoy/match-clj.wat"
    "probes/annoy/match-kw.wat"
    "probes/annoy/println-arity.wat"
    "probes/annoy/println-watast.wat"
    "probes/annoy/quote-shorthand-empty.wat"
    "probes/annoy/quote-shorthand.wat"
    "probes/annoy/typealias-clj.wat"
    "probes/annoy/typealias-kwname.wat"
    "probes/annoy/variadic-plus.wat"
    "probes/annoy/when.wat"
    "probes/aoc/conj-subs-scaling.wat"
    "probes/aoc/map-insert-scaling.wat"
    "probes/aoc/nth-scaling.wat"
    "probes/aoc/parse-cost.wat"
    "probes/aoc/persistent-arity-control.wat"
    "probes/aoc/persistent-arity.wat"
    "probes/aoc/persistent-insert-scaling.wat"
    "probes/aoc/persistent-nested-type-alias.wat"
    "probes/aoc/persistent-nested-type-control.wat"
    "probes/aoc/persistent-nested-type.wat"
    "probes/aoc/persistent-valuetype-control.wat"
    "probes/aoc/persistent-valuetype.wat"
    "probes/aoc/sorted-structures.wat"
    "probes/aoc/vector-scaling.wat"
    "probes/arena-cycle.wat"
    "probes/assert-fail.wat"
    "probes/assert-pass.wat"
    "probes/ast-to-num-eval.wat"
    "probes/call-result-as-head.wat"
    "probes/cell-closures.wat"
    "probes/cell-global-def-clj.wat"
    "probes/cell-global-def.wat"
    "probes/cell-handle-drop.wat"
    "probes/clj-let-body-unchecked.wat"
    "probes/clj-let-kwcalls-mixed.wat"
    "probes/clj-let-lambda-parametric.wat"
    "probes/clj-let-lambda.wat"
    "probes/clj-let-mixed.wat"
    "probes/clj-let-symcalls-mixed.wat"
    "probes/ctor-kw-concrete.wat"
    "probes/ctor-wat-type-concrete.wat"
    "probes/curried-closure.wat"
    "probes/doctest/equals-on-enum.wat"
    "probes/doctest/examples-census.wat"
    "probes/doctest/examples-count.wat"
    "probes/doctest/guarded-compare.wat"
    "probes/doctest/unmask-failures.wat"
    "probes/doctest/variant-spelling.wat"
    "probes/err/catch-cost.wat"
    "probes/err/error-in-stream.wat"
    "probes/err/try-catches-assertion.wat"
    "probes/err/try-catches-what.wat"
    "probes/euler/bigint-digits-route.wat"
    "probes/euler/bigint-divide.wat"
    "probes/euler/bigint-surface.wat"
    "probes/euler/bigint-to-string.wat"
    "probes/euler/char-at-cost.wat"
    "probes/euler/char-at-exponent.wat"
    "probes/euler/char-at-scaling.wat"
    "probes/euler/letter-lookup-cost.wat"
    "probes/euler/regex-find.wat"
    "probes/euler/regex-replace.wat"
    "probes/euler/regex-surface.wat"
    "probes/euler/string-sort-order.wat"
    "probes/euler/string-split-empty.wat"
    "probes/fmt/corpus.wat"
    "probes/fmt/smoke.wat"
    "probes/fmt/throughput.wat"
    "probes/fn-parametric-param-kw.wat"
    "probes/fn-parametric-param.wat"
    "probes/fn-type-two-args.wat"
    "probes/fn-typed-param-clj.wat"
    "probes/fn-typed-param-kw.wat"
    "probes/generic-kv-fn-kwctor.wat"
    "probes/generic-kv-fn-literal.wat"
    "probes/generic-kv-fn.wat"
    "probes/grep/facts-invariants.wat"
    "probes/grep/written-is-exact.wat"
    "probes/holon/bind-lossiness.wat"
    "probes/holon/coincident-semantics.wat"
    "probes/holon/vsa-algebra.wat"
    "probes/interp-data.wat"
    "probes/java/builtin-verb-as-value.wat"
    "probes/java/extend-type-partial.wat"
    "probes/java/old-visitor-on-new-shape.wat"
    "probes/java/peer-messages-conflicting-type.wat"
    "probes/java/peer-messages-outside-type.wat"
    "probes/java/peer-messages-shared-type-twice.wat"
    "probes/java/peer-messages-shared-type.wat"
    "probes/java/struct-in-pure-enum.wat"
    "probes/java/variant-equality-inline.wat"
    "probes/java/variant-equality-let.wat"
    "probes/java/variant-equality.wat"
    "probes/java/visitor-surface-concrete.wat"
    "probes/java/visitor-surface-generic.wat"
    "probes/koans/anon-fn-literal.wat"
    "probes/koans/bigint-compare.wat"
    "probes/koans/bigint-literal.wat"
    "probes/koans/defmacro-macroexpand.wat"
    "probes/koans/first-last.wat"
    "probes/koans/generic-vector-constructor.wat"
    "probes/koans/hashset-elements.wat"
    "probes/koans/keyword-as-function.wat"
    "probes/koans/keyword-lookup-equals.wat"
    "probes/koans/literal-rows.wat"
    "probes/koans/map-as-function.wat"
    "probes/koans/record-accessor-generic-map.wat"
    "probes/koans/record-accessor-generic.wat"
    "probes/koans/rest-of-empty.wat"
    "probes/koans/str-arity.wat"
    "probes/kw-let-body-checked.wat"
    "probes/kw-let-mixed.wat"
    "probes/learner/ch01-mutant.wat"
    "probes/learner/enum-with-fn-field.wat"
    "probes/learner/f64-in-failure-record.wat"
    "probes/learner/f64-printing.wat"
    "probes/learner/fn-types-and-calls.wat"
    "probes/learner/hashmap-i64-f64.wat"
    "probes/learner/i64-overflow.wat"
    "probes/learner/string-to-f64.wat"
    "probes/length-of-string.wat"
    "probes/let-fn-later-binding.wat"
    "probes/let-fn-unknown-symbol.wat"
    "probes/letcc-early-exit.wat"
    "probes/letrec-let-bound-fn.wat"
    "probes/letrec-named-fn.wat"
    "probes/lint/catches-what.wat"
    "probes/lint/end-span.wat"
    "probes/lint/ladder-trigger.wat"
    "probes/lint/self.wat"
    "probes/lint/stdlib.wat"
    "probes/load/lib.wat"
    "probes/load/main.wat"
    "probes/main-keyword.wat"
    "probes/main-symbol.wat"
    "probes/mal/function-call-cost.wat"
    "probes/mal/read-frame-raw.wat"
    "probes/mal/read-frame-unbalanced.wat"
    "probes/mal/service-roundtrip-cost.wat"
    "probes/mal/stdin-repl.wat"
    "probes/mal/user-guide-stdin-echo.wat"
    "probes/match-binder-catchall.wat"
    "probes/match-missing-arm.wat"
    "probes/match-wildcard-enum.wat"
    "probes/mk/alias-param-and-fn-vector.wat"
    "probes/mk/amp-symbol.wat"
    "probes/mk/ch09-mutant.wat"
    "probes/mk/clj-let-into.wat"
    "probes/mk/defmacro-clj-kwname.wat"
    "probes/mk/defmacro-clj.wat"
    "probes/mk/defmacro-kw-clj-params.wat"
    "probes/mk/fn-vector.wat"
    "probes/mk/lib-macros.wat"
    "probes/mk/lib-surface.wat"
    "probes/mk/logo-heavy.wat"
    "probes/mk/macro-arg-data-kw.wat"
    "probes/mk/macro-arg-data-sym.wat"
    "probes/mk/macro-arg-program-body.wat"
    "probes/mk/macro-arg-variants.wat"
    "probes/mk/macro-arrow-user-steps.wat"
    "probes/mk/macro-calls-defn.wat"
    "probes/mk/macro-template-kw-quote.wat"
    "probes/mk/macros-symbol-head.wat"
    "probes/mk/macros.wat"
    "probes/mk/option-stream-bare-none.wat"
    "probes/mk/option-stream-brace-none.wat"
    "probes/mk/quote-bare-symbol.wat"
    "probes/mk/quote-kw-head.wat"
    "probes/mk/recursive-enum.wat"
    "probes/mk/some-direct.wat"
    "probes/mk/some-in-stream-alias-typed-let.wat"
    "probes/mk/some-in-stream-no-alias.wat"
    "probes/mk/some-in-vector.wat"
    "probes/mk/some-via-helper.wat"
    "probes/mk/splice-list-form-program-body.wat"
    "probes/mk/splice-list-form.wat"
    "probes/mk/splice-vector-form-program-body.wat"
    "probes/mk/splice-vector-form.wat"
    "probes/mk/surface.wat"
    "probes/mk/typealias-fn.wat"
    "probes/mk/unit-variant-bare-arg.wat"
    "probes/mk/unit-variant-bare-colons.wat"
    "probes/mk/unit-variant-bare.wat"
    "probes/mk/unit-variant-call.wat"
    "probes/mk/vector-conj-10000.wat"
    "probes/mk/vector-conj-20000.wat"
    "probes/mk/vector-conj-40000.wat"
    "probes/mk/very-recursiveo-1000.wat"
    "probes/mk/very-recursiveo-10000.wat"
    "probes/mk/very-recursiveo-100000.wat"
    "probes/mk/very-recursiveo-20000.wat"
    "probes/mk/vr-count-10000.wat"
    "probes/mk/vr-count-20000.wat"
    "probes/mk/vr-reify-linear-10000.wat"
    "probes/mk/vr-stream-10000.wat"
    "probes/mk/vr-stream-kwlet.wat"
    "probes/mk/vr-stream-nolet.wat"
    "probes/mk/vr-take-1000.wat"
    "probes/mk/vr-take-10000.wat"
    "probes/mk/vr-take-20000.wat"
    "probes/ml/constructor-as-fn.wat"
    "probes/ml/enum-holding-fn.wat"
    "probes/ml/functor-dictionary.wat"
    "probes/ml/generic-recursive-enum.wat"
    "probes/ml/mutual-recursive-enums.wat"
    "probes/ml/nested-pattern-hole.wat"
    "probes/ml/nested-pattern-latent.wat"
    "probes/ml/nested-pattern-positional.wat"
    "probes/ml/nested-pattern-vector.wat"
    "probes/ml/nested-pattern.wat"
    "probes/ml/newtype-construct.wat"
    "probes/ml/newtype-equal.wat"
    "probes/ml/newtype-plus.wat"
    "probes/ml/newtype-unwrap-0.wat"
    "probes/ml/newtype-unwrap-inner.wat"
    "probes/ml/newtype-unwrap-value.wat"
    "probes/ml/newtype-value.wat"
    "probes/ml/signature-functor.wat"
    "probes/ml/surface-concrete-param.wat"
    "probes/ml/surface-seqable-control.wat"
    "probes/ml/tuple-in-variant-binders.wat"
    "probes/ml/tuple-in-variant-nested.wat"
    "probes/ml/tuple-in-variant-strict.wat"
    "probes/ml/tuple-let-clj.wat"
    "probes/ml/tuple-let-kw.wat"
    "probes/ml/tuple-match-binders.wat"
    "probes/ml/tuple-match-variants.wat"
    "probes/ml/tuple-of-variants-claim.wat"
    "probes/ml/type-claim-refused.wat"
    "probes/name-ampersand.wat"
    "probes/name-gt.wat"
    "probes/name-leading-star.wat"
    "probes/name-lt.wat"
    "probes/named-fn-as-value.wat"
    "probes/num-to-ast.wat"
    "probes/paip/ast-as-data.wat"
    "probes/paip/dotted-pattern.wat"
    "probes/paip/renamed-symbol.wat"
    "probes/paip/vector-contains.wat"
    "probes/prover/ast-to-source.wat"
    "probes/prover/ch01-mutant.wat"
    "probes/prover/first-step.wat"
    "probes/prover/j-bob-lang-smoke.wat"
    "probes/prover/jbob-as-data.wat"
    "probes/prover/lt-symbol.wat"
    "probes/prover/nil-t-in-data.wat"
    "probes/prover/read-jbob-source.wat"
    "probes/quote-empty-keyword-nested.wat"
    "probes/quote-empty-keyword.wat"
    "probes/quote-empty-nested.wat"
    "probes/quote-empty-symbol.wat"
    "probes/rete/accumulator-count-leak.wat"
    "probes/rete/accumulator-empty-pass.wat"
    "probes/rete/derived-multiplicity-tally.wat"
    "probes/rete/derived-multiplicity.wat"
    "probes/rete/explain-support.wat"
    "probes/rete/fire-once-oracle-empty.wat"
    "probes/rete/fire-verbs-compared.wat"
    "probes/rete/insert-native-vs-oracle.wat"
    "probes/rete/native-vs-oracle-tally.wat"
    "probes/rete/native-vs-oracle.wat"
    "probes/rete/retraction-scenarios.wat"
    "probes/service-counter.wat"
    "probes/service-fn-put.wat"
    "probes/service-fn-state-impure.wat"
    "probes/service-fn-state.wat"
    "probes/sexp-cons.wat"
    "probes/sexp-primitives.wat"
    "probes/sicp/connect-bare-address.wat"
    "probes/sicp/connect-return-type.wat"
    "probes/sicp/peer-as-parameter.wat"
    "probes/sicp/self-referential-stream.wat"
    "probes/sicp/stream-memo.wat"
    "probes/some-fn-widens.wat"
    "probes/sqlite/cell-rendering.wat"
    "probes/sqlite/errors-are-values.wat"
    "probes/sqlite/readonly-reads.wat"
    "probes/sqlite/readonly-refuses-write.wat"
    "probes/sqlite/transaction-abort.wat"
    "probes/type-watast-core.wat"
    "probes/type-watast-kw.wat"
    "probes/type-watast-slash.wat"
    "probes/typer/ast-children-cost.wat"
    "probes/typer/ch01-mutant.wat"
    "probes/typer/first-of-empty-vector.wat"
    "probes/typer/read-pie-arith-names.wat"
    "probes/typer/read-pie-equality-names.wat"
    "probes/typer/read-pie-unicode-accented-symbol.wat"
    "probes/typer/read-pie-unicode-arrow-string.wat"
    "probes/typer/read-pie-unicode-lambda-symbol.wat"
    "probes/typer/read-pie.wat"
    "probes/typer/unicode-in-source.wat"
    "probes/typer/value-copy-cost.wat"
    "probes/unknown-bare-in-defn.wat"
    "probes/unknown-bare-in-main.wat"
    "probes/unknown-ns-in-fn.wat"
    "probes/y-generic-kwfn.wat"
    "probes/y-generic.wat"
    "probes/z-combinator.wat"
    "rete/lib/check.wat"
    "rete/r01-chaining.wat"
    "rete/r02-retraction.wat"
    "sicp/ch31-local-state.wat"
    "sicp/ch33-mutable-data.wat"
    "sicp/ch34-concurrency.wat"
    "sicp/ch35-streams.wat"
    "sicp/lib/account.wat"
    "sicp/lib/check.wat"
    "sqlite/lib/check.wat"
    "sqlite/s01-crud.wat"
    "store/lib/check.wat"
    "store/q01-two-backends.wat"
))

(:wat::core::defn :user::main [] -> :wat::core::nil
  (:wat::core::let
    [ns (:wat::core::mapv :we::report (:we::paths))
     total (:wat::core::foldl
             (:wat::core::fn [a <- :wat::core::i64 n <- :wat::core::i64] -> :wat::core::i64
               (:wat::core::+ a n))
             0 ns)]
    (:wat::kernel::println (:wat::string::concat "TOTAL-UNWRITTEN " (:wat::i64::to-string total)))))
