;; oracle/ch01-02.clj: the queries of books/reasoned-schemer/ch01-playthings.wat and
;; ch02-old-toys.wat, in the oracle. Each line must equal the wat chapter's expectation.
;; Run: clojure -M oracle/ch01-02.clj
(load-file "oracle/mk.clj")
(in-ns 'mk)

(load-file "oracle/rels.clj")

(println "== ch01")
(show "fail" (run* q fail))
(show "succeed" (run* q succeed))
(show "pea-pod" (run* q (== 'pea 'pod)))
(show "q=pea" (run* q (== q 'pea)))
(show "pea=q" (run* q (== 'pea q)))
(show "fresh-unused" (run* q (fresh (x) (== 'pea q))))
(show "fresh-fused" (run* q (fresh (x) (== x q))))
(show "fresh-list" (run* q (fresh (x) (== (lst x) q))))
(show "fused-pea" (run* q (fresh (x) (== x q) (== 'pea x))))
(show "q=(x y),y=x" (run* q (fresh (x y) (== (lst q y) (lst (lst x y) x)))))
(show "shadow" (run* x (fresh (x) (== 'pea x))))
(show "conj2-corn" (run* q (conj2 succeed (== 'corn q))))
(show "conj2-fail" (run* q (conj2 fail (== 'corn q))))
(show "olive-and-oil" (run* q (conj2 (== 'olive q) (== 'oil q))))
(show "olive-or-fail" (run* q (disj2 (== 'olive q) fail)))
(show "olive-or-oil" (run* q (disj2 (== 'olive q) (== 'oil q))))
(show "oil" (run* x (disj2 (conj2 (== 'olive x) fail) (== 'oil x))))
(show "oil-olive" (run* x (disj2 (== 'oil x) (conj2 (== 'olive x) succeed))))
(show "virgin" (run* x (disj2 (conj2 (== 'virgin x) fail) (disj2 (== 'olive x) (disj2 succeed (== 'oil x))))))
(show "split-pea-r" (run* r (fresh (x) (fresh (y) (== 'split x) (== 'pea y) (== (lst x y) r)))))
(show "split-pea-xy" (run* (x y) (== 'split x) (== 'pea y)))
(show "conde-split" (run* (x y) (conde ((== 'split x) (== 'pea y)) ((== 'red x) (== 'bean y)))))
(show "conde-oil" (run* x (conde ((== 'olive x) fail) ((== 'oil x)))))
(show "lentil" (run* (x y) (conde ((fresh (z) (== 'lentil z))) ((== x y)))))
(show "teacupo" (run* x (teacupo x)))
(show "teacupo2" (run* (x y) (teacupo x) (teacupo y)))
(show "teacupo-true" (run* (x y) (conde ((teacupo x) (== true y)) ((== false x) (== true y)))))
(show "teacupo-false" (run* (x y) (conde ((teacupo x) (teacupo x)) ((== false x) (teacupo y)))))

(println "== ch02")
(show "caro" (run* q (caro (quo '(a c o r n)) q)))
(show "caro-a" (run* q (caro (quo '(a c o r n)) 'a)))
(show "caro-pear" (run* r (fresh (x y) (caro (lst r y) x) (== 'pear x))))
(show "grape-a" (run* r (fresh (x y) (caro (quo '(grape raisin pear)) x) (caro (quo '((a) (b) (c))) y) (== (kons x y) r))))
(show "cdro-o" (run* r (fresh (v) (cdro (quo '(a c o r n)) v) (fresh (w) (cdro v w) (caro w r)))))
(show "cdro-x" (run* x (cdro (quo '(c o r n)) (lst x 'r 'n))))
(show "acorn" (run* l (fresh (x) (cdro l (quo '(c o r n))) (caro l x) (== 'a x))))
(show "conso-l" (run* l (conso (quo '(a b c)) (quo '(d e)) l)))
(show "conso-x" (run* x (conso x (quo '(a b c)) (quo '(d a b c)))))
(show "eadc" (run* r (fresh (x y z) (== (lst 'e 'a 'd x) r) (conso y (lst 'a z 'c) r))))
(show "conso-d" (run* x (conso x (lst 'a x 'c) (lst 'd 'a x 'c))))
(show "dadc" (run* l (fresh (x) (== (lst 'd 'a x 'c) l) (conso x (lst 'a x 'c) l))))
(show "nullo-grape" (run* q (nullo (quo '(grape raisin pear)))))
(show "nullo-nil" (run* q (nullo ())))
(show "nullo-x" (run* x (nullo x)))
(show "pairo-qq" (run* q (pairo (kons q q))))
(show "pairo-nil" (run* q (pairo ())))
(show "pairo-atom" (run* q (pairo 'pair)))
(show "pairo-x" (run* x (pairo x)))
(show "pairo-r" (run* r (pairo (kons r ()))))
(show "single-a" (run* q (singletono (quo '(a)))))
(show "single-ab" (run* q (singletono (quo '(a b)))))
(show "single-x" (run* x (singletono x)))
