;; oracle/ch03.clj: the queries of books/reasoned-schemer/ch03-old-friends.wat, in the oracle.
;; Its output is the wat chapter's expected values.
;; Run: clojure -M oracle/ch03.clj
(load-file "oracle/mk.clj")
(in-ns 'mk)
(load-file "oracle/rels.clj")

(println "== ch03")
(show "listo-fresh-elem" (run* x (listo (lst 'a 'b x 'd))))
(show "listo-tail-1" (run 1 x (listo (lst* '[a b c] x))))
(show "listo-tail-5" (run 5 x (listo (lst* '[a b c] x))))
(show "lolo-1" (run 1 l (lolo l)))
(show "lolo-fresh" (run* q (fresh (x y) (lolo (lst (quo '(a b)) (lst x 'c) (lst 'd y))))))
(show "lolo-tail-1" (run 1 x (lolo (lst* [(quo '(a b)) (quo '(c d))] x))))
(show "lolo-tail-5" (run 5 x (lolo (lst* [(quo '(a b)) (quo '(c d))] x))))
(show "lolo-5" (run 5 x (lolo x)))
(show "loso-tail-1" (run 1 z (loso (lst* [(quo '(g))] z))))
(show "loso-tail-5" (run 5 z (loso (lst* [(quo '(g))] z))))
(show "loso-4" (run 4 r (fresh (w x y z) (loso (lst* [(quo '(g)) (kons 'e w) (kons x y)] z)) (== (lst w (kons x y) z) r))))
(show "membero-olive" (run* q (membero 'olive (quo '(virgin olive oil)))))
(show "membero-1" (run 1 y (membero y (quo '(hummus with pita)))))
(show "membero-all" (run* y (membero y (quo '(hummus with pita)))))
(show "membero-e" (run* y (membero 'e (lst 'pasta y 'fagioli))))
(show "membero-x" (run* x (membero 'e (lst 'pasta 'e x 'fagioli))))
(show "membero-xy" (run* (x y) (membero 'e (lst 'pasta x 'fagioli y))))
(show "membero-q" (run* q (fresh (x y) (== (lst 'pasta x 'fagioli y) q) (membero 'e q))))
(show "membero-tofu-1" (run 1 l (membero 'tofu l)))
(show "membero-tofu-5" (run 5 l (membero 'tofu l)))
(show "proper-membero-5" (run 5 l (proper-membero 'tofu l)))
