;; oracle/rels.clj: the relations of books/reasoned-schemer/lib/, defined identically in the
;; oracle. Load after oracle/mk.clj, inside (in-ns 'mk). Keep each definition the same shape
;; as its wat twin (same conde lines, same goal order), or the answer order may differ.

;; ch 1
(defrel (teacupo t) (disj2 (== 'tea t) (== 'cup t)))

;; ch 2
(defrel (caro p a) (fresh (d) (== (kons a d) p)))
(defrel (cdro p d) (fresh (a) (== (kons a d) p)))
(defrel (conso a d p) (== (kons a d) p))
(defrel (nullo x) (== () x))
(defrel (pairo p) (fresh (a d) (conso a d p)))
(defrel (singletono l) (fresh (a) (== (lst a) l)))

;; ch 3
(defrel (listo l)
  (conde ((nullo l))
         ((fresh (d) (cdro l d) (listo d)))))

(defrel (lolo l)
  (conde ((nullo l))
         ((fresh (a) (caro l a) (listo a))
          (fresh (d) (cdro l d) (lolo d)))))

(defrel (loso l)
  (conde ((nullo l))
         ((fresh (a) (caro l a) (singletono a))
          (fresh (d) (cdro l d) (loso d)))))

(defrel (membero x l)
  (conde ((caro l x))
         ((fresh (d) (cdro l d) (membero x d)))))

(defrel (proper-membero x l)
  (conde ((caro l x) (fresh (d) (cdro l d) (listo d)))
         ((fresh (d) (cdro l d) (proper-membero x d)))))

;; ch 4
(defrel (appendo l t out)
  (conde ((nullo l) (== t out))
         ((fresh (a d res) (conso a d l) (conso a res out) (appendo d t res)))))

(defrel (swappendo l t out)
  (conde ((fresh (a d res) (conso a d l) (conso a res out) (swappendo d t res)))
         ((nullo l) (== t out))))

(defrel (unwrapo x out)
  (conde ((fresh (a) (caro x a) (unwrapo a out)))
         ((== x out))))

;; ch 5
(defrel (memo x l out)
  (conde ((caro l x) (== l out))
         ((fresh (d) (cdro l d) (memo x d out)))))

(defrel (rembero x l out)
  (conde ((nullo l) (== () out))
         ((conso x out l))
         ((fresh (a d res) (conso a d l) (conso a res out) (rembero x d res)))))

(defrel (surpriseo s)
  (rembero s (quo '(a b c)) (quo '(a b c))))

;; ch 6
(defrel (alwayso) (conde (succeed) ((alwayso))))
(defrel (nevero) (nevero))
(defrel (very-recursiveo)
  (conde ((nevero)) ((very-recursiveo)) ((alwayso)) ((very-recursiveo)) ((nevero))))

;; ch 7: numbers are little-endian lists of bits, () is zero, and the last bit is always 1
(defn build-num [n]
  (cond (zero? n) ()
        (odd? n) (kons 1 (build-num (quot (dec n) 2)))
        :else (kons 0 (build-num (quot n 2)))))

(defrel (bit-xoro x y r)
  (conde ((== 0 x) (== 0 y) (== 0 r))
         ((== 0 x) (== 1 y) (== 1 r))
         ((== 1 x) (== 0 y) (== 1 r))
         ((== 1 x) (== 1 y) (== 0 r))))

(defrel (bit-ando x y r)
  (conde ((== 0 x) (== 0 y) (== 0 r))
         ((== 1 x) (== 0 y) (== 0 r))
         ((== 0 x) (== 1 y) (== 0 r))
         ((== 1 x) (== 1 y) (== 1 r))))

(defrel (half-addero x y r c)
  (bit-xoro x y r)
  (bit-ando x y c))

(defrel (full-addero b x y r c)
  (fresh (w xy wz)
    (half-addero x y w xy)
    (half-addero w b r wz)
    (bit-xoro xy wz c)))

(defrel (poso n) (fresh (a d) (== (kons a d) n)))
(defrel (>1o n) (fresh (a ad dd) (== (lst* [a ad] dd) n)))

(declare gen-addero)
(defrel (addero b n m r)
  (conde ((== 0 b) (== () m) (== n r))
         ((== 0 b) (== () n) (== m r) (poso m))
         ((== 1 b) (== () m) (addero 0 n (quo '(1)) r))
         ((== 1 b) (== () n) (poso m) (addero 0 (quo '(1)) m r))
         ((== (quo '(1)) n) (== (quo '(1)) m)
          (fresh (a c) (== (lst a c) r) (full-addero b 1 1 a c)))
         ((== (quo '(1)) n) (gen-addero b n m r))
         ((== (quo '(1)) m) (>1o n) (>1o r) (addero b (quo '(1)) n r))
         ((>1o n) (gen-addero b n m r))))

(defrel (gen-addero b n m r)
  (fresh (a c d e x y z)
    (== (kons a x) n)
    (== (kons d y) m) (poso y)
    (== (kons c z) r) (poso z)
    (full-addero b a d c e)
    (addero e x y z)))

(defrel (+o n m k) (addero 0 n m k))
(defrel (-o n m k) (+o m k n))

(defrel (lengtho l n)
  (conde ((nullo l) (== () n))
         ((fresh (d res) (cdro l d) (+o (quo '(1)) res n) (lengtho d res)))))

;; ch 8, part one: multiplication, comparison, division
(declare odd-*o bound-*o)
(defrel (*o n m p)
  (conde ((== () n) (== () p))
         ((poso n) (== () m) (== () p))
         ((== (quo '(1)) n) (poso m) (== m p))
         ((>1o n) (== (quo '(1)) m) (== n p))
         ((fresh (x z)
            (== (kons 0 x) n) (poso x)
            (== (kons 0 z) p) (poso z)
            (>1o m)
            (*o x m z)))
         ((fresh (x y)
            (== (kons 1 x) n) (poso x)
            (== (kons 0 y) m) (poso y)
            (*o m n p)))
         ((fresh (x y)
            (== (kons 1 x) n) (poso x)
            (== (kons 1 y) m) (poso y)
            (odd-*o x n m p)))))

(defrel (odd-*o x n m p)
  (fresh (q)
    (bound-*o q p n m)
    (*o x m q)
    (+o (kons 0 q) m p)))

(defrel (bound-*o q p n m)
  (conde ((== () q) (poso p))
         ((fresh (a0 a1 a2 a3 x y z)
            (== (kons a0 x) q)
            (== (kons a1 y) p)
            (conde ((== () n) (== (kons a2 z) m) (bound-*o x y z ()))
                   ((== (kons a3 z) n) (bound-*o x y z m)))))))

(defrel (=lo n m)
  (conde ((== () n) (== () m))
         ((== (quo '(1)) n) (== (quo '(1)) m))
         ((fresh (a x b y)
            (== (kons a x) n) (poso x)
            (== (kons b y) m) (poso y)
            (=lo x y)))))

(defrel (<lo n m)
  (conde ((== () n) (poso m))
         ((== (quo '(1)) n) (>1o m))
         ((fresh (a x b y)
            (== (kons a x) n) (poso x)
            (== (kons b y) m) (poso y)
            (<lo x y)))))

(defrel (<=lo n m)
  (conde ((=lo n m))
         ((<lo n m))))

(defrel (<o n m)
  (conde ((<lo n m))
         ((=lo n m) (fresh (x) (poso x) (+o n x m)))))

(defrel (<=o n m)
  (conde ((== n m))
         ((<o n m))))

(defrel (splito n r l h)
  (conde ((== () n) (== () h) (== () l))
         ((fresh (b n2)
            (== (lst* [0 b] n2) n) (== () r)
            (== (kons b n2) h) (== () l)))
         ((fresh (n2)
            (== (kons 1 n2) n) (== () r)
            (== n2 h) (== (quo '(1)) l)))
         ((fresh (b n2 a r2)
            (== (lst* [0 b] n2) n)
            (== (kons a r2) r) (== () l)
            (splito (kons b n2) r2 () h)))
         ((fresh (n2 a r2)
            (== (kons 1 n2) n)
            (== (kons a r2) r) (== (quo '(1)) l)
            (splito n2 r2 () h)))
         ((fresh (b n2 a r2 l2)
            (== (kons b n2) n)
            (== (kons a r2) r)
            (== (kons b l2) l)
            (poso l2)
            (splito n2 r2 l2 h)))))

(declare n-wider-than-mo)
(defrel (divo n m q r)
  (conde ((== () q) (== n r) (<o n m))
         ((== (quo '(1)) q) (=lo m n) (+o r m n) (<o r m))
         ((poso q) (<lo m n) (<o r m) (n-wider-than-mo n m q r))))

(defrel (n-wider-than-mo n m q r)
  (fresh (nh nl qh ql)
    (fresh (mql mrql rr rh)
      (splito n r nl nh)
      (splito q r ql qh)
      (conde ((== () nh) (== () qh) (-o nl r mql) (*o m ql mql))
             ((poso nh)
              (*o m ql mql)
              (+o r mql mrql)
              (-o mrql nl rr)
              (splito rr r () rh)
              (divo nh m qh rh))))))

;; ch 8, part two: logarithm and exponent
(declare exp2o base-three-or-moreo repeated-mulo)
(defrel (logo n b q r)
  (conde ((== (quo '(1)) n) (poso b) (== () q) (== () r))
         ((== () q) (<o n b) (+o r (quo '(1)) n))
         ((== (quo '(1)) q) (>1o b) (=lo n b) (+o r b n))
         ((== (quo '(1)) b) (poso q) (+o r (quo '(1)) n))
         ((== () b) (poso q) (== r n))
         ((== (quo '(0 1)) b)
          (fresh (a ad dd)
            (poso dd)
            (== (lst* [a ad] dd) n)
            (exp2o n () q)
            (fresh (s) (splito n dd r s))))
         ((<=o (quo '(1 1)) b) (<lo b n)
          (base-three-or-moreo n b q r))))

(defrel (exp2o n b q)
  (conde ((== (quo '(1)) n) (== () q))
         ((>1o n) (== (quo '(1)) q)
          (fresh (s) (splito n b s (quo '(1)))))
         ((fresh (q1 b2)
            (== (kons 0 q1) q) (poso q1)
            (<lo b n)
            (appendo b (kons 1 b) b2)
            (exp2o n b2 q1)))
         ((fresh (q1 nh b2 s)
            (== (kons 1 q1) q) (poso q1)
            (poso nh)
            (splito n b s nh)
            (appendo b (kons 1 b) b2)
            (exp2o nh b2 q1)))))

(defrel (base-three-or-moreo n b q r)
  (fresh (bw1 bw nw nw1 ql1 ql s)
    (exp2o b () bw1)
    (+o bw1 (quo '(1)) bw)
    (<lo q n)
    (fresh (q1 bwq1)
      (+o q (quo '(1)) q1)
      (*o bw q1 bwq1)
      (<o nw1 bwq1))
    (exp2o n () nw1)
    (+o nw1 (quo '(1)) nw)
    (divo nw bw ql1 s)
    (+o ql (quo '(1)) ql1)
    (<=lo ql q)
    (fresh (bql qh s2 qdh qd)
      (repeated-mulo b ql bql)
      (divo nw bw1 qh s2)
      (+o ql qdh qh)
      (+o ql qd q)
      (<=o qd qdh)
      (fresh (bqd bq1 bq)
        (repeated-mulo b qd bqd)
        (*o bql bqd bq)
        (*o b bq bq1)
        (+o bq r n)
        (<o n bq1)))))

(defrel (repeated-mulo n q nq)
  (conde ((poso n) (== () q) (== (quo '(1)) nq))
         ((== (quo '(1)) q) (== n nq))
         ((>1o q)
          (fresh (q1 nq1)
            (+o q1 (quo '(1)) q)
            (repeated-mulo n q1 nq1)
            (*o nq1 n nq)))))

(defrel (expo b q n) (logo n b q ()))
