;; ch01-mutant.wat: books/little-prover/ch01-transcript.wat with ONE expected answer made wrong
;; ("(quote ham)" -> "(quote eggs)"), to prove the generated checks really run. Expected: fails there.
;; GENERATED by tools/jbob2wat.wat. Do not edit by hand.
;; The Little Prover, chapter 1: every entry of the book's transcript for this chapter
;; (vendor/j-bob/little-prover.scm), run through J-Bob translated into wat and checked against
;; guile's J-Bob (oracle/prover.expected.tsv). Chapters from 3 on build on the definitions
;; before them, so they load every transcript chapter from 3 up to their own.
;;
;; Run: wat books/little-prover/ch01-transcript.wat   (exit 0 and a final "ok" line = pass)

(:wat::load-file! "../../books/little-schemer/lib/ch01-toys.wat")
(:wat::load-file! "../../books/little-schemer/lib/ch04-numbers-games.wat")
(:wat::load-file! "../../books/little-prover/lib/j-bob-lang.wat")
(:wat::load-file! "../../books/little-prover/lib/j-bob.wat")
(:wat::load-file! "../../books/little-prover/lib/transcript-ch01.wat")

(:wat::core::defn :user::main [] -> :wat::core::nil
  (:wat::core::do
    ;; chapter1.example1
    (:wat::test::assert-eq (:wat::core::ast->source :jb::chapter1_example1)
                           "(quote eggs)")
    ;; chapter1.example2
    (:wat::test::assert-eq (:wat::core::ast->source :jb::chapter1_example2)
                           "(quote t)")
    ;; chapter1.example3
    (:wat::test::assert-eq (:wat::core::ast->source :jb::chapter1_example3)
                           "(quote nil)")
    ;; chapter1.example4
    (:wat::test::assert-eq (:wat::core::ast->source :jb::chapter1_example4)
                           "(quote nil)")
    ;; chapter1.example5
    (:wat::test::assert-eq (:wat::core::ast->source :jb::chapter1_example5)
                           "(quote nil)")
    ;; chapter1.example6
    (:wat::test::assert-eq (:wat::core::ast->source :jb::chapter1_example6)
                           "(quote t)")
    ;; chapter1.example7
    (:wat::test::assert-eq (:wat::core::ast->source :jb::chapter1_example7)
                           "(quote t)")
    ;; chapter1.example8
    (:wat::test::assert-eq (:wat::core::ast->source :jb::chapter1_example8)
                           "(quote t)")
    ;; chapter1.example9
    (:wat::test::assert-eq (:wat::core::ast->source :jb::chapter1_example9)
                           "(equal (cons (quote bagels) (quote (and lox))) (cons x y))")
    ;; chapter1.example10
    (:wat::test::assert-eq (:wat::core::ast->source :jb::chapter1_example10)
                           "(cons y (equal (cdr x) (equal (atom x) (quote nil))))")
    ;; chapter1.example11
    (:wat::test::assert-eq (:wat::core::ast->source :jb::chapter1_example11)
                           "(cons y (equal (car (cons (car (cons (cdr x) (car y))) (quote (oats)))) (equal (atom x) (atom (cons (atom b) (equal c (cons a b)))))))")
    ;; chapter1.example12
    (:wat::test::assert-eq (:wat::core::ast->source :jb::chapter1_example12)
                           "(atom (car a))")
    (:wat::kernel::println "little-prover ch01 transcript: ok")))
