;; j-bob-lang-smoke.wat: J-Bob's primitives in wat (books/little-prover/lib/j-bob-lang.wat)
;; give J-Bob's answers. Each check is J-Bob's own semantics from vendor/j-bob/j-bob-lang.scm.
(:wat::load-file! "../../books/little-schemer/lib/ch01-toys.wat")
(:wat::load-file! "../../books/little-schemer/lib/ch04-numbers-games.wat")
(:wat::load-file! "../../books/little-prover/lib/j-bob-lang.wat")
(wat.core/defn user/main [] :- wat.type/nil
  (wat.core/do
    (wat.test/assert-eq (jb/car '(ham eggs)) 'ham)
    (wat.test/assert-eq (jb/car 'ham) '())
    (wat.test/assert-eq (jb/cdr '(ham eggs)) '(eggs))
    (wat.test/assert-eq (jb/cons 'ham '(eggs)) '(ham eggs))
    (wat.test/assert-eq (jb/atom '()) 't)
    (wat.test/assert-eq (jb/atom '(a)) 'nil)
    (wat.test/assert-eq (jb/equal '(a b) '(a b)) 't)
    (wat.test/assert-eq (jb/equal 'a 'b) 'nil)
    (wat.test/assert-eq (jb/natp '3) 't)
    (wat.test/assert-eq (jb/natp '-3) 'nil)
    (wat.test/assert-eq (jb/natp 'x) 'nil)
    (wat.test/assert-eq (jb/plus '2 '3) '5)
    (wat.test/assert-eq (jb/plus 'x '3) '3)
    (wat.test/assert-eq (jb/lt '2 '3) 't)
    (wat.test/assert-eq (jb/size '(a (b c))) '4)
    (wat.test/assert-eq (jb/true? 'nil) false)
    (wat.test/assert-eq (jb/true? '()) true)
    (wat.kernel/println "j-bob-lang smoke: ok")))
