;; GENERATED by tools/jbob2wat.wat. Do not edit by hand.
;; The Little Prover, chapter 2: every entry of the book's transcript for this chapter
;; (vendor/j-bob/little-prover.scm), run through J-Bob translated into wat and checked against
;; guile's J-Bob (oracle/prover.expected.tsv). Chapters from 3 on build on the definitions
;; before them, so they load every transcript chapter from 3 up to their own.
;;
;; Run: wat books/little-prover/ch02-transcript.wat   (exit 0 and a final "ok" line = pass)

(:wat::load-file! "../little-schemer/lib/ch01-toys.wat")
(:wat::load-file! "../little-schemer/lib/ch04-numbers-games.wat")
(:wat::load-file! "lib/j-bob-lang.wat")
(:wat::load-file! "lib/j-bob.wat")
(:wat::load-file! "lib/transcript-ch02.wat")

(:wat::core::defn :user::main [] -> :wat::core::nil
  (:wat::core::do
    ;; chapter2.example1
    (:wat::test::assert-eq (:wat::core::ast->source :jb::chapter2_example1)
                           "(if (if (equal a (quote t)) (quote t) (equal (quote or) (quote (black coffee)))) c c)")
    ;; chapter2.example2
    (:wat::test::assert-eq (:wat::core::ast->source :jb::chapter2_example2)
                           "(if (atom (car a)) (if (equal (car a) (cdr a)) (quote hominy) (quote grits)) (if (equal (cdr (car a)) (quote (hash browns))) (cons (quote ketchup) (cons (car (car a)) (quote (hash browns)))) (cons (quote mustard) (car a))))")
    ;; chapter2.example3
    (:wat::test::assert-eq (:wat::core::ast->source :jb::chapter2_example3)
                           "(cons (quote statement) (if (equal a (quote question)) (cons (cons n (quote (answer))) (cons n (quote (other answer)))) (cons (cons n (quote (else))) (cons n (quote (other else))))))")
    (:wat::kernel::println "little-prover ch02 transcript: ok")))
