#!/usr/bin/env bash
# tools/gen-refuse.sh: regenerate the compiler's NEGATIVE tests.
#
# elf/refuse.wat and elf/refuse-nonascii.wat are elf/compile.wat with a one-line driver, pointed
# at a program it cannot translate. They are generated rather than maintained so that they are
# the SAME compiler -- a negative test that has drifted from the thing it tests proves nothing.
#
# Both are excluded from ./run.sh, because a program that is supposed to fail cannot pass.
# tools/elf-run.sh runs them and checks the message.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

gen () {   # out-file, source-to-compile, what-it-proves
  local out="$1" src="$2" why="$3"
  { printf ';; %s -- the compiler'"'"'s NEGATIVE test: the same compiler, pointed at a program\n' "$out"
    printf ';; it cannot translate. %s\n' "$why"
    printf ';;\n;; GENERATED by tools/gen-refuse.sh. Everything below is elf/compile.wat with a\n'
    printf ';; different driver; edit that file, not this one.\n;;\n\n'
    sed '/^(:wat::core::defn :user::main/,$d' elf/compile.wat
    printf '(:wat::core::defn :user::main [] -> :wat::core::nil\n'
    printf '  (:c::compile "%s" "elf/out/bad.elf"))\n' "$src"
  } > "$out"
  echo "wrote $out ($(wc -l < "$out") lines)"
}

gen elf/refuse.wat          elf/bad/unsupported.wat \
    'It must die naming the form it could not compile.'
gen elf/refuse-nonascii.wat elf/bad/nonascii.wat \
    'A string value is measured in BYTES and wat measures strings in CHARACTERS, so anything
;; outside ASCII is refused rather than silently mis-measured (F-120).'
gen elf/refuse-arity.wat    elf/bad/arity.wat \
    'A call with the wrong number of arguments used to COMPILE: the stack stayed balanced and
;; the callee read its parameters from the wrong slots (F-128).'
gen elf/refuse-ptradd.wat   elf/bad/ptradd.wat \
    'A String is an address, and adding to one is not arithmetic. The type pass always knew
;; enough to say so and did not (F-128).'
