;; elf/refuse-nonascii.wat -- the compiler's NEGATIVE test: the same compiler, pointed at a program
;; it cannot translate. A string value is measured in BYTES and wat measures strings in CHARACTERS, so anything
;; outside ASCII is refused rather than silently mis-measured (F-120).
;;
;; GENERATED by tools/gen-refuse.sh. Everything below is elf/compile.wat with a
;; different driver; edit that file, not this one.
;;

;; elf/compile.wat — a compiler from wat source to a native x86-64 Linux executable, in wat.
;;
;; `elf/hello.wat` emits a binary this file's author chose. This one is given a wat PROGRAM and
;; emits a binary for it: it reads the source with `:wat::core::read-string`, walks the AST it
;; gets back, and generates machine code for what it finds. Nothing is pasted -- every
;; instruction, every immediate, every jump distance and every address is computed from the
;; program being compiled.
;;
;; The whole front end is three verbs wat already has:
;;
;;   `:wat::core::read-string`    source text -> a `:wat::WatAST`
;;   `:wat::core::ast-kind`       "list", "symbol", "int", "string", "vector", "keyword"
;;   `:wat::core::ast->children`  a node's children
;;   `:wat::core::ast->source`    a node's text, which is the literal for ints and the name for
;;                                symbols, so `ast-name` is never needed
;;
;; That wat can take its own source apart is the reason this is a compiler and not a code
;; generator with a hard-coded program.
;;
;; ## The language it accepts
;;
;;   (wat.core/defn user/NAME [p :- wat.type/i64 ...] :- T  BODY...)
;;   (wat.core/if COND THEN ELSE)          a real forward branch, patched
;;   (wat.core/let [a E b E] BODY...)      slots in the frame, innermost shadowing outward
;;   (wat.core/do BODY...)                 a sequence; the last form is the value
;;   (user/NAME args...)                   a call, arguments on the stack, recursion included --
;;                                         and a SELF call in tail position becomes a jmp, because
;;                                         wat has TCO and a compiler for wat therefore owes it
;;   (wat.kernel/println EXPR | "literal")
;;   (wat.core/+ - * quot rem)             n-ary, folded left
;;   (wat.core/< > <= >= = not=)           cmp + setcc + movzx, so a bool is 0 or 1 in rax
;;   (wat.string/concat A B ...)           n-ary, folded left through `str_cat`
;;   (wat.string/length S)                 a peek at the string's header
;;   nil, true, false                      a machine zero, a one and a zero
;;   integer literals, negatives included, nested to any depth
;;   string literals, as VALUES: a pointer to [len:8][bytes...] in the data tail
;;
;; and an INTRINSIC set that is the compiler's own, not wat's:
;;
;;   (wat.os/getpid) (wat.os/getppid) (wat.os/fork)     a bare syscall, result in rax
;;   (wat.os/exit N)                                     exit(N)
;;   (wat.os/wait)                                       wait4, answering the raw status
;;   (wat.os/mmap N)                                     anonymous read+write memory
;;   (wat.os/clone SP)                                   a child sharing the address space
;;   (wat.os/peek A) (wat.os/poke A V)                   eight bytes at an address
;;
;; Both spellings of every name are accepted -- `wat.core/+` and `:wat::core::+` -- because the
;; reader keeps whichever the source used and this repository writes one while the migration
;; targets the other.
;;
;; Anything else is a COMPILE ERROR that names the form it could not translate, which is the
;; least a compiler owes its caller.
;;
;; ## Where the compiled language stops being wat
;;
;; Everything in the first list is wat, and `elf/src/*.wat` is checked by running each program
;; BOTH ways and requiring identical output. Nothing in the second list is: the interpreter has
;; no `wat.os/fork`, so `elf/native/*.wat` cannot be run by it at all and has no differential
;; oracle. That is the same position a C compiler is in with `write` -- it does not implement it
;; either -- and C's answer is libc. wat has no equivalent: its OS surface (`:wat::io::`,
;; `:wat::kernel::spawn-*`) is implemented in Rust inside the interpreter, so a compiled program
;; cannot reach it. **F-119** is that gap, found by walking into it.
;;
;; ## The code it generates
;;
;; A stack discipline, which is the obvious thing and also the only thing available without a
;; register allocator: every expression leaves its value in `rax`, and a binary operator
;; evaluates its left side, pushes it, evaluates its right side, and pops.
;;
;;   48 b8 <imm64>   mov rax, literal
;;   50              push rax
;;   48 89 c1        mov rcx, rax
;;   58              pop rax
;;   48 01 c8        add rax, rcx
;;   48 29 c8        sub rax, rcx
;;   48 0f af c1     imul rax, rcx
;;   e8 <rel32>      call print_i64        -- a real relocation, computed in pass two
;;
;; ## Two passes, over the whole program
;;
;; A call needs the callee's address, and a callee's address depends on the length of everything
;; placed before it -- so one function cannot be compiled without knowing about all of them. Pass
;; one compiles every function with every address zero, purely to measure; the addresses then
;; follow from the lengths; pass two compiles again with the real table. Every immediate and
;; every displacement is fixed width, so the passes are the same length, and the compiler ASSERTS
;; that function by function.
;;
;; Forward branches inside a function are not predicted, they are PATCHED: `if` emits its `jz`
;; with a zero operand, compiles the branch, and overwrites the operand once it knows how far it
;; went. That is F-104 again -- no positional update -- on a String, so the patch is a `subs`
;; either side of the hole. Crafting Interpreters chapter 23 (C-106) is the same problem on a
;; Vector.
;;
;; ## The calling convention
;;
;; Arguments are pushed left to right and popped by the caller. Inside the callee, rbp points at
;; the saved rbp, so argument i of n is at [rbp + 16 + 8*(n-1-i)] and `let` slots are below at
;; [rbp - 8*(slot+1)]. The frame size is worked out before the body is compiled, by walking it
;; for the deepest simultaneous `let` demand.
;;
;; The entry point is a 19-byte stub -- `call user/main`, then exit(0) -- which is the only code
;; in the output not compiled from a `defn`.
;;
;; ## Strings, and the heap
;;
;; A String value is one machine word, like everything else: the address of `[len:8][bytes...]`.
;; Literals live in the read-only data tail. Anything `concat` builds lives in a megabyte the
;; entry stub `mmap`s, bump-allocated through **r15**, which is reserved for the program's whole
;; life and is the entire memory model -- no free, no collector, no bounds check.
;;
;; The header length is in BYTES, and `:wat::string::length` counts CHARACTERS. They agree only
;; for ASCII, so a non-ASCII literal is refused rather than silently mis-measured; wat has no
;; byte-length verb to compile against. See F-120, and `elf/bad/nonascii.wat`.
;;
;; ## The runtime
;;
;; Four routines, 435 bytes, the only part of the output not computed from the source, and the
;; part a C toolchain would call libc for:
;;
;;   `print_i64`  105 bytes   sign handling, a divide-by-ten loop building digits backwards on
;;                            the stack, and one `write`. Checked against four values (a
;;                            negative, a small one, zero, and i64::MAX) before it was embedded.
;;   `str_cat`     97 bytes   two lengths added, a header written at the heap top, two copy
;;                            loops, r15 bumped.
;;   `print_str`  158 bytes   wat's EDN escaping, in machine code.
;;   `print_bool`  75 bytes   `true` and `false` built on the stack, so it needs no relocation.
;;
;; That last one is the interesting one. `println` renders a String as EDN, so agreeing with the
;; interpreter means reproducing its escaping exactly -- and every escape in it was found by
;; ASKING the interpreter what it printed, because nothing says. **F-120** is that gap.
;;
;; Run from the repository root:
;;   wat elf/compile.wat        # compiles elf/src/*.wat to elf/out/*.elf and verifies each
;;   tools/elf-run.sh           # chmod +x, run them, compare their output

(:wat::load-file! "lib/asm.wat")

;; ---------------------------------------------------------------- the runtime
;;
;;   push rbp / mov rbp,rsp / sub rsp,32        a 32-byte digit buffer on the stack
;;   lea rsi,[rbp-1] / mov byte [rsi],10        newline goes in last
;;   test rax,rax / jns / neg rax / mov r8,1    remember and remove the sign
;;   mov rcx,10 / xor rdx,rdx / div rcx         digits, least significant first
;;   add dl,'0' / mov [rsi],dl / dec rsi        written backwards into the buffer
;;   test rax,rax / jnz                         until the value is used up
;;   cmp r8,0 / je / mov byte [rsi],'-'         put the sign back
;;   lea rdx,[rbp-1] / sub rdx,rsi / inc rdx    length = end - start + 1
;;   mov rax,1 / mov rdi,1 / syscall            write(1, rsi, rdx)
;;   leave / ret
(:wat::core::defn :c::rt-print-i64 [] -> :wat::core::String
  (:wat::string::concat
    "554889e54883ec20488d75ffc6060a48ffce4d31c04885c0790a48f7d8"
    "49c7c00100000048c7c10a0000004831d248f7f180c230881648ffce48"
    "85c075ed4983f8007406c6062d48ffce48ffc6488d55ff4829f248ffc2"
    "48c7c00100000048c7c7010000000f05c9c3"))

;; `str_cat(rax = a, rcx = b) -> rax`, 97 bytes. The two lengths are added, the total is written
;; at the heap top, the bytes are copied across with two byte-at-a-time loops, and r15 is bumped
;; past the result rounded up to eight. r10 carries the result pointer, because rax is needed as
;; the copy loops' scratch byte.
;;
;;   mov r8,[rax] / mov r9,[rcx]                 the two lengths
;;   lea rdx,[rax+8] / lea rcx,[rcx+8]           the two sources
;;   mov rax,r8 / add rax,r9 / mov [r15],rax     total, written as the new header
;;   mov r10,r15 / lea rdi,[r15+8]               result pointer and destination cursor
;;   add rax,15 / and rax,-8 / add r15,rax       bump, rounded up
;;   <copy r8 bytes> <copy r9 bytes>
;;   mov rax,r10 / ret
(:wat::core::defn :c::rt-str-cat [] -> :wat::core::String
  (:wat::string::concat
    "4c8b004c8b09488d5008488d49084c89c04c01c84989074d89fa498d7f08"
    "4883c00f4883e0f84901c74889d64d89c34d85db740f8a06880748ffc648"
    "ffc749ffcbebec4889ce4d89cb4d85db740f8a06880748ffc648ffc749ff"
    "cbebec4c89d0c3"))

;; `print_str(rax = s)`, 158 bytes. **This routine is wat's EDN escaping, in machine code.**
;; `:wat::kernel::println` renders a String as EDN -- quotes around it, and quote, backslash,
;; newline, tab and carriage return escaped, everything else passed through raw -- so agreeing
;; with the interpreter means doing exactly that: a quote, a byte loop that emits one byte or
;; two, a quote, a newline, and ONE write. The escaped copy is built at the heap top WITHOUT
;; bumping r15, because nothing allocates while a string is being printed.
;;
;; Every one of those five escapes was found by ASKING THE INTERPRETER, not by reading a
;; specification, because there is no specification. That is F-120.
(:wat::core::defn :c::rt-print-str [] -> :wat::core::String
  (:wat::string::concat
    "4989c04d8b08498d70084c89ff4d89fac6072248ffc74d31db4d39cb7d5a"
    "8a063c2274173c5c74133c0a741c3c0974263c0d7430880748ffc7eb35c6"
    "075c48ffc7880748ffc7eb28c6075c48ffc7c6076e48ffc7eb1ac6075c48"
    "ffc7c6077448ffc7eb0cc6075c48ffc7c6077248ffc748ffc649ffc3eba1"
    "c6072248ffc7c6070a48ffc74889fa4c29d24c89d648c7c70100000048c7"
    "c0010000000f05c3"))

;; `print_bool(rax)`, 75 bytes. `true` and `false` are built on the stack a word at a time --
;; "true" is one `mov` of 0x65757274 and a newline byte -- so this routine needs no data section
;; and no relocation, the same trick `print_i64` uses for its digit buffer.
(:wat::core::defn :c::rt-print-bool [] -> :wat::core::String
  (:wat::string::concat
    "554889e54883ec104885c07414c745f874727565c645fc0a48c7c205000000"
    "eb14c745f866616c7366c745fc650a48c7c206000000488d75f848c7c00100"
    "000048c7c7010000000f05c9c3"))

(:wat::core::defn :c::runtime [] -> :wat::core::String
  (:wat::string::concat (:c::rt-print-i64) (:c::rt-str-cat) (:c::rt-print-str)
                        (:c::rt-print-bool)))

;; how many bytes a hex string is
(:wat::core::defn :c::hexlen [h <- :wat::core::String] -> :wat::core::i64
  (:wat::core::/ (:wat::string::length h) 2))

;; the three entry points, laid out in that order at `rt`
(:wat::core::defn :c::at-i64 [rt <- :wat::core::i64] -> :wat::core::i64 rt)
(:wat::core::defn :c::at-cat [rt <- :wat::core::i64] -> :wat::core::i64
  (:wat::core::+ rt (:c::hexlen (:c::rt-print-i64))))
(:wat::core::defn :c::at-str [rt <- :wat::core::i64] -> :wat::core::i64
  (:wat::core::+ (:c::at-cat rt) (:c::hexlen (:c::rt-str-cat))))
(:wat::core::defn :c::at-bool [rt <- :wat::core::i64] -> :wat::core::i64
  (:wat::core::+ (:c::at-str rt) (:c::hexlen (:c::rt-print-str))))

;; ---------------------------------------------------------------- instructions

(:wat::core::defn :c::mov-rax [n <- :wat::core::i64] -> :wat::core::String
  (:wat::string::concat "48b8" (:asm::le n 8)))
(:wat::core::defn :c::mov-rdi [n <- :wat::core::i64] -> :wat::core::String
  (:wat::string::concat "48bf" (:asm::le n 8)))
(:wat::core::defn :c::mov-rsi [n <- :wat::core::i64] -> :wat::core::String
  (:wat::string::concat "48be" (:asm::le n 8)))
(:wat::core::defn :c::mov-rdx [n <- :wat::core::i64] -> :wat::core::String
  (:wat::string::concat "48ba" (:asm::le n 8)))
;; mov [rbp+disp32], rax   and   mov rax, [rbp+disp32]
(:wat::core::defn :c::store [d <- :wat::core::i64] -> :wat::core::String
  (:wat::string::concat "488985" (:asm::le d 4)))
(:wat::core::defn :c::load [d <- :wat::core::i64] -> :wat::core::String
  (:wat::string::concat "488b85" (:asm::le d 4)))
;; the registers a Linux syscall takes its arguments in
(:wat::core::defn :c::mov-r10 [n <- :wat::core::i64] -> :wat::core::String
  (:wat::string::concat "49ba" (:asm::le n 8)))
(:wat::core::defn :c::mov-r8 [n <- :wat::core::i64] -> :wat::core::String
  (:wat::string::concat "49b8" (:asm::le n 8)))
(:wat::core::defn :c::mov-r9 [n <- :wat::core::i64] -> :wat::core::String
  (:wat::string::concat "49b9" (:asm::le n 8)))
(:wat::core::defn :c::mov-rdi-rax [] -> :wat::core::String "4889c7")
(:wat::core::defn :c::mov-rsi-rax [] -> :wat::core::String "4889c6")

(:wat::core::defn :c::sub-rsp [n <- :wat::core::i64] -> :wat::core::String
  (:wat::string::concat "4881ec" (:asm::le n 4)))
(:wat::core::defn :c::add-rsp [n <- :wat::core::i64] -> :wat::core::String
  (:wat::string::concat "4881c4" (:asm::le n 4)))

(:wat::core::defn :c::op-hex [op <- :wat::core::String] -> :wat::core::String
  (:wat::core::cond
    ((:wat::core::= op "+") "4801c8")       ;; add rax, rcx
    ((:wat::core::= op "-") "4829c8")       ;; sub rax, rcx
    ((:wat::core::= op "*") "480fafc1")     ;; imul rax, rcx
    ;; idiv wants the dividend sign-extended into rdx:rax, which is what cqo is for
    ((:wat::core::= op "quot") "489948f7f9")            ;; cqo ; idiv rcx  -> quotient in rax
    ((:wat::core::= op "rem") "489948f7f94889d0")       ;; cqo ; idiv rcx ; mov rax, rdx

    ;; a comparison is cmp + setcc + movzx, so a bool is an ordinary 0 or 1 in rax
    (:else (:wat::string::concat "4839c8" (:c::setcc op) "480fb6c0"))))

(:wat::core::defn :c::setcc [op <- :wat::core::String] -> :wat::core::String
  (:wat::core::cond
    ((:wat::core::= op "<") "0f9cc0")
    ((:wat::core::= op ">") "0f9fc0")
    ((:wat::core::= op "<=") "0f9ec0")
    ((:wat::core::= op ">=") "0f9dc0")
    ((:wat::core::= op "=") "0f94c0")
    (:else "0f95c0")))

;; ---------------------------------------------------------------- the output being built

(:wat::core::defrecord :c::Out
  [base <- :wat::core::i64  code <- :wat::core::String  tail <- :wat::core::String])

(:wat::core::defn :c::emit [o <- :c::Out hex <- :wat::core::String] -> :c::Out
  (:wat::core::assoc o :code (:wat::string::concat (:c::Out/code o) hex)))

(:wat::core::defn :c::codelen [o <- :c::Out] -> :wat::core::i64
  (:wat::core::/ (:wat::string::length (:c::Out/code o)) 2))

;; the virtual address of the next instruction, which is what a relocation needs
(:wat::core::defn :c::here [o <- :c::Out] -> :wat::core::i64
  (:wat::core::+ (:c::Out/base o) (:c::codelen o)))

(:wat::core::defn :c::call [o <- :c::Out target <- :wat::core::i64] -> :c::Out
  (:c::emit o (:wat::string::concat "e8"
    (:asm::le (:wat::core::- target (:wat::core::+ (:c::here o) 5)) 4))))

;; **A jump is patched, not predicted.** A forward branch's distance is not known until the code
;; it jumps over exists, so the operand is emitted as four zero bytes and overwritten afterwards.
;; That is F-104 again -- no positional update -- on a String this time, so the patch is a `subs`
;; either side of the hole. Crafting Interpreters chapter 23 (C-106) is the same problem, and
;; there it was a Vector.
(:wat::core::defn :c::patch [o <- :c::Out off <- :wat::core::i64 hex <- :wat::core::String] -> :c::Out
  (:wat::core::let [code (:c::Out/code o)
                    at (:wat::core::* off 2)]
    (:wat::core::assoc o :code
      (:wat::string::concat
        (:wat::string::subs code 0 at)
        hex
        (:wat::string::subs code (:wat::core::+ at (:wat::string::length hex)) (:wat::string::length code))))))

;; ---------------------------------------------------------------- names, in both spellings

(:wat::core::defn :c::is? [src <- :wat::core::String clj <- :wat::core::String kw <- :wat::core::String] -> :wat::core::bool
  (:wat::core::or (:wat::core::= src clj) (:wat::core::= src kw)))

(:wat::core::defn :c::binop [src <- :wat::core::String] -> :wat::core::String
  (:wat::core::cond
    ((:c::is? src "wat.core/+" ":wat::core::+") "+")
    ((:c::is? src "wat.core/-" ":wat::core::-") "-")
    ((:c::is? src "wat.core/*" ":wat::core::*") "*")
    ((:c::is? src "wat.core/quot" ":wat::core::quot") "quot")
    ((:c::is? src "wat.core/rem" ":wat::core::rem") "rem")
    ((:c::is? src "wat.core/<" ":wat::core::<") "<")
    ((:c::is? src "wat.core/>" ":wat::core::>") ">")
    ((:c::is? src "wat.core/<=" ":wat::core::<=") "<=")
    ((:c::is? src "wat.core/>=" ":wat::core::>=") ">=")
    ((:c::is? src "wat.core/=" ":wat::core::=") "=")
    ((:c::is? src "wat.core/not=" ":wat::core::not=") "not=")
    (:else "")))

;; ---- the compiler's INTRINSICS: verbs that become a syscall rather than a call
;;
;; This is the first point where the compiled language stops being a subset of wat. The
;; interpreter has no `wat.os/fork`, so a program using these cannot be run by it, and the
;; differential test that carried every earlier program does not apply. That is not a trick: it
;; is the same position a C compiler is in with `write`, which it does not implement either. The
;; difference is that C's answer is libc and wat's answer would have to be an intrinsic present
;; in BOTH worlds -- which is a real requirement for the builder's roadmap, stated here because
;; this is the file that ran into it.
(:wat::core::defn :c::syscall-nr [s <- :wat::core::String] -> :wat::core::i64
  (:wat::core::cond
    ((:c::is? s "wat.os/getpid" ":wat::os::getpid") 39)
    ((:c::is? s "wat.os/fork" ":wat::os::fork") 57)
    ((:c::is? s "wat.os/getppid" ":wat::os::getppid") 110)
    (:else -1)))

(:wat::core::defn :c::exit? [s <- :wat::core::String] -> :wat::core::bool
  (:c::is? s "wat.os/exit" ":wat::os::exit"))
(:wat::core::defn :c::wait? [s <- :wat::core::String] -> :wat::core::bool
  (:c::is? s "wat.os/wait" ":wat::os::wait"))
;; one-argument intrinsics that take their argument in a register other than rdi
(:wat::core::defn :c::mmap? [s <- :wat::core::String] -> :wat::core::bool
  (:c::is? s "wat.os/mmap" ":wat::os::mmap"))
(:wat::core::defn :c::clone? [s <- :wat::core::String] -> :wat::core::bool
  (:c::is? s "wat.os/clone" ":wat::os::clone"))
(:wat::core::defn :c::peek? [s <- :wat::core::String] -> :wat::core::bool
  (:c::is? s "wat.os/peek" ":wat::os::peek"))
(:wat::core::defn :c::poke? [s <- :wat::core::String] -> :wat::core::bool
  (:c::is? s "wat.os/poke" ":wat::os::poke"))

(:wat::core::defn :c::do? [s <- :wat::core::String] -> :wat::core::bool
  (:c::is? s "wat.core/do" ":wat::core::do"))

(:wat::core::defn :c::println? [s <- :wat::core::String] -> :wat::core::bool
  (:c::is? s "wat.kernel/println" ":wat::kernel::println"))
(:wat::core::defn :c::concat? [s <- :wat::core::String] -> :wat::core::bool
  (:c::is? s "wat.string/concat" ":wat::string::concat"))
(:wat::core::defn :c::strlen? [s <- :wat::core::String] -> :wat::core::bool
  (:c::is? s "wat.string/length" ":wat::string::length"))
(:wat::core::defn :c::if? [s <- :wat::core::String] -> :wat::core::bool
  (:c::is? s "wat.core/if" ":wat::core::if"))
(:wat::core::defn :c::let? [s <- :wat::core::String] -> :wat::core::bool
  (:c::is? s "wat.core/let" ":wat::core::let"))
(:wat::core::defn :c::defn? [s <- :wat::core::String] -> :wat::core::bool
  (:c::is? s "wat.core/defn" ":wat::core::defn"))

(:wat::core::defn :c::fail [what <- :wat::core::String a <- :wat::WatAST] -> :c::Out
  (:wat::kernel::assertion-failed!
    :message (:wat::string::concat "compile: cannot compile " what ": " (:wat::core::ast->source a))))

(:wat::core::defn :c::to-int [s <- :wat::core::String] -> :wat::core::i64
  (:wat::core::match (:wat::string::to-i64 s)
    [:wat::core::Option.Some {:value n} n]
    [:wat::core::Option.None {}
      (:wat::kernel::assertion-failed! :message (:wat::string::concat "compile: not an integer: " s))]))

(:wat::core::defn :c::kind [a <- :wat::WatAST] -> :wat::core::String
  (:wat::core::str (:wat::core::ast-kind a)))

;; ---------------------------------------------------------------- scopes and functions

(:wat::core::typealias :c::Kids (:wat::core::Vector :- [:wat::WatAST]))

;; a name and where it lives, as a displacement from rbp: parameters above it, locals below
(:wat::core::defrecord :c::Bind
  [name <- :wat::core::String  disp <- :wat::core::i64  ty <- :wat::core::String])
(:wat::core::typealias :c::Env (:wat::core::Vector :- [:c::Bind]))

;; innermost first, so a `let` shadows a parameter of the same name
(:wat::core::defn :c::lookup [env <- :c::Env name <- :wat::core::String i <- :wat::core::i64] -> :wat::core::i64
  (:wat::core::cond
    ((:wat::core::< i 0) 999999)
    ((:wat::core::= (:c::Bind/name (:wat::core::nth env i)) name) (:c::Bind/disp (:wat::core::nth env i)))
    (:else (:c::lookup env name (:wat::core::- i 1)))))

(:wat::core::defn :c::lookup-ty [env <- :c::Env name <- :wat::core::String i <- :wat::core::i64] -> :wat::core::String
  (:wat::core::cond
    ((:wat::core::< i 0) "i64")
    ((:wat::core::= (:c::Bind/name (:wat::core::nth env i)) name) (:c::Bind/ty (:wat::core::nth env i)))
    (:else (:c::lookup-ty env name (:wat::core::- i 1)))))

(:wat::core::defrecord :c::Fn
  [name <- :wat::core::String  node <- :wat::WatAST  addr <- :wat::core::i64
   ret <- :wat::core::String])
(:wat::core::typealias :c::Fns (:wat::core::Vector :- [:c::Fn]))

(:wat::core::defn :c::fn-ret [fns <- :c::Fns name <- :wat::core::String i <- :wat::core::i64] -> :wat::core::String
  (:wat::core::cond
    ((:wat::core::>= i (:wat::core::length fns)) "i64")
    ((:wat::core::= (:c::Fn/name (:wat::core::nth fns i)) name) (:c::Fn/ret (:wat::core::nth fns i)))
    (:else (:c::fn-ret fns name (:wat::core::+ i 1)))))

(:wat::core::defn :c::fn-addr [fns <- :c::Fns name <- :wat::core::String i <- :wat::core::i64] -> :wat::core::i64
  (:wat::core::cond
    ((:wat::core::>= i (:wat::core::length fns)) -1)
    ((:wat::core::= (:c::Fn/name (:wat::core::nth fns i)) name) (:c::Fn/addr (:wat::core::nth fns i)))
    (:else (:c::fn-addr fns name (:wat::core::+ i 1)))))

;; the body of a `defn` is every child from the first list onwards, which skips the name, the
;; parameter vector and the return type without caring which spelling they were in
(:wat::core::defn :c::body-start [ks <- :c::Kids i <- :wat::core::i64] -> :wat::core::i64
  (:wat::core::cond
    ((:wat::core::>= i (:wat::core::length ks)) i)
    ((:wat::core::= (:c::kind (:wat::core::nth ks i)) "list") i)
    (:else (:c::body-start ks (:wat::core::+ i 1)))))

;; ---------------------------------------------------------------- what type an expression has
;;
;; The compiler needs this for exactly one decision -- which of the two print routines `println`
;; should call -- but that one decision reaches everywhere, because the argument can be a name, a
;; branch, a call or a `let`. So there is a small static type pass, with two types: a machine
;; word (`i64`) and a pointer to a string header (`str`).
;;
;; It is deliberately not inference. Every type is DECLARED somewhere -- on a parameter, on a
;; `defn`'s return -- and this walk only propagates what the declarations already say. A wat type
;; is recognised by its spelling, which covers `wat.type/String` and `:wat::core::String` without
;; a table.

(:wat::core::defn :c::ty-of-node [a <- :wat::WatAST] -> :wat::core::String
  (:wat::core::let [src (:wat::core::ast->source a)]
    (:wat::core::cond
      ((:wat::string::contains? src "String") "str")
      ((:wat::string::contains? src "bool") "bool")
      ((:wat::string::contains? src "nil") "nil")
      (:else "i64"))))

;; a comparison answers a bool; everything else `:c::binop` names answers a machine word
(:wat::core::defn :c::cmp? [op <- :wat::core::String] -> :wat::core::bool
  (:wat::core::or (:wat::core::= op "<") (:wat::core::= op ">")
    (:wat::core::or (:wat::core::= op "<=") (:wat::core::= op ">=")
      (:wat::core::or (:wat::core::= op "=") (:wat::core::= op "not=")))))

(:wat::core::defn :c::type-of [a <- :wat::WatAST env <- :c::Env fns <- :c::Fns] -> :wat::core::String
  (:wat::core::let [k (:c::kind a)]
    (:wat::core::cond
      ((:wat::core::= k "string") "str")
      ((:wat::core::= k "nil") "nil")
      ((:wat::core::= k "bool") "bool")
      ((:wat::core::= k "symbol") (:c::lookup-ty env (:wat::core::ast->source a)
                                    (:wat::core::- (:wat::core::length env) 1)))
      ((:wat::core::= k "list") (:c::type-of-form (:wat::core::ast->children a) env fns))
      (:else "i64"))))

(:wat::core::defn :c::type-of-form [ks <- :c::Kids env <- :c::Env fns <- :c::Fns] -> :wat::core::String
  (:wat::core::if (:wat::core::= (:wat::core::length ks) 0) "i64"
    (:wat::core::let [head (:wat::core::ast->source (:wat::core::nth ks 0))
                      last (:wat::core::nth ks (:wat::core::- (:wat::core::length ks) 1))]
      (:wat::core::cond
        ((:c::concat? head) "str")
        ((:c::println? head) "nil")
        ;; a branch is typed by its consequent; the alternative has to agree, and if it does not
        ;; the program is wrong in a way this compiler does not check
        ((:c::if? head) (:c::type-of (:wat::core::nth ks 2) env fns))
        ((:c::do? head) (:c::type-of last env fns))
        ((:c::let? head)
          (:c::type-of last
            (:c::ty-bind (:wat::core::ast->children (:wat::core::nth ks 1)) 0 env fns) fns))
        ((:c::cmp? (:c::binop head)) "bool")
        ((:wat::core::>= (:c::fn-addr fns head 0) 0) (:c::fn-ret fns head 0))
        (:else "i64")))))

;; the same left-to-right walk `:c::bind-each` does, carrying types instead of displacements
(:wat::core::defn :c::ty-bind [bs <- :c::Kids i <- :wat::core::i64 env <- :c::Env fns <- :c::Fns] -> :c::Env
  (:wat::core::if (:wat::core::>= i (:wat::core::length bs)) env
    (:c::ty-bind bs (:wat::core::+ i 2)
      (:wat::core::conj env
        (:c::Bind :name (:wat::core::ast->source (:wat::core::nth bs i)) :disp 0
                  :ty (:c::type-of (:wat::core::nth bs (:wat::core::+ i 1)) env fns)))
      fns)))

;; ---------------------------------------------------------------- string literals, as values
;;
;; A string VALUE is one machine word: the address of `[len:8][bytes...]`, so it fits the same
;; one-register model everything else uses. Literals live in the read-only data tail; anything
;; `concat` builds lives in the heap the entry stub mmaps.
;;
;; The header length is in BYTES, and `:wat::string::length` counts CHARACTERS -- they agree only
;; for ASCII, which is why a non-ASCII literal is refused rather than silently mis-measured. The
;; refusal comes for free: `:asm::code-of` has no code for it and says "not encodable". wat has
;; no byte-length verb to compile against; see F-120.

(:wat::core::defn :c::unescape [s <- :wat::core::String i <- :wat::core::i64 acc <- :wat::core::String] -> :wat::core::String
  (:wat::core::if (:wat::core::>= i (:wat::string::length s)) acc
    (:wat::core::let [c (:wat::string::subs s i (:wat::core::+ i 1))]
      (:wat::core::if (:wat::core::and (:wat::core::= c "\\")
                        (:wat::core::< (:wat::core::+ i 1) (:wat::string::length s)))
        (:c::unescape s (:wat::core::+ i 2)
          (:wat::string::concat acc
            (:wat::core::let [d (:wat::string::subs s (:wat::core::+ i 1) (:wat::core::+ i 2))]
              (:wat::core::cond
                ((:wat::core::= d "n") "\n")
                ((:wat::core::= d "t") "\t")
                ((:wat::core::= d "r") "\r")
                (:else d)))))
        (:c::unescape s (:wat::core::+ i 1) (:wat::string::concat acc c))))))

(:wat::core::defn :c::zeros [n <- :wat::core::i64 acc <- :wat::core::String] -> :wat::core::String
  (:wat::core::if (:wat::core::<= n 0) acc
    (:c::zeros (:wat::core::- n 1) (:wat::string::concat acc "00"))))

;; a header is eight bytes, so the bytes after it are padded back up to a multiple of eight
(:wat::core::defn :c::str-lit [a <- :wat::WatAST o <- :c::Out tb <- :wat::core::i64] -> :c::Out
  (:wat::core::let
    [src (:wat::core::ast->source a)
     text (:c::unescape (:wat::string::subs src 1 (:wat::core::- (:wat::string::length src) 1)) 0 "")
     n (:wat::string::length text)
     addr (:wat::core::+ tb (:wat::core::/ (:wat::string::length (:c::Out/tail o)) 2))
     pad (:wat::core::rem (:wat::core::- 8 (:wat::core::rem n 8)) 8)
     o1 (:wat::core::assoc o :tail
          (:wat::string::concat (:c::Out/tail o) (:asm::le n 8) (:asm::ascii text 0 "")
            (:c::zeros pad "")))]
    (:c::emit o1 (:c::mov-rax addr))))

;; ---------------------------------------------------------------- frame size
;;
;; A `let` needs a slot per binding, and the prologue has to reserve them before the body is
;; compiled -- so the compiler walks the body first and takes the deepest simultaneous demand.
;; Slots are never reused between sibling `let`s, which costs stack and buys simplicity.

(:wat::core::defn :c::imax [a <- :wat::core::i64 b <- :wat::core::i64] -> :wat::core::i64
  (:wat::core::if (:wat::core::> a b) a b))

(:wat::core::defn :c::slots-of [a <- :wat::WatAST] -> :wat::core::i64
  (:wat::core::if (:wat::core::not (:wat::core::= (:c::kind a) "list")) 0
    (:wat::core::let [ks (:wat::core::ast->children a)]
      (:wat::core::if (:wat::core::= (:wat::core::length ks) 0) 0
        (:wat::core::if (:c::let? (:wat::core::ast->source (:wat::core::nth ks 0)))
          (:wat::core::+ (:wat::core::/ (:wat::core::length (:wat::core::ast->children (:wat::core::nth ks 1))) 2)
            (:c::imax (:c::slots-list (:wat::core::ast->children (:wat::core::nth ks 1)) 0 0)
                      (:c::slots-list ks 2 0)))
          (:c::slots-list ks 0 0))))))

(:wat::core::defn :c::slots-list [ks <- :c::Kids i <- :wat::core::i64 best <- :wat::core::i64] -> :wat::core::i64
  (:wat::core::if (:wat::core::>= i (:wat::core::length ks)) best
    (:c::slots-list ks (:wat::core::+ i 1) (:c::imax best (:c::slots-of (:wat::core::nth ks i))))))

(:wat::core::defn :c::slots-body [ks <- :c::Kids i <- :wat::core::i64 best <- :wat::core::i64] -> :wat::core::i64
  (:c::slots-list ks i best))

;; ---------------------------------------------------------------- tail calls
;;
;; **wat eliminates tail calls, so a compiler for wat has to.** A million levels of tail
;; self-recursion return `1000000` under the interpreter; the same depth NOT in tail position
;; dumps core. So iteration in wat is a tail-recursive loop, and a compiler that lays every call
;; down as a `call` turns working programs into segmentation faults. `elf/src/deep.wat` is that
;; program, and before this it segfaulted at exit 139 while the interpreter printed 1000000.
;;
;; A self tail call is a `jmp` back to the top of the body with the arguments replaced:
;;
;;   <evaluate each new argument, pushing it>    left to right, as an ordinary call would
;;   pop rax ; mov [rbp+16], rax                 then popped BACK into the incoming slots,
;;   pop rax ; mov [rbp+24], rax                 last argument first, because it is on top
;;   jmp body                                    and round again, on the same frame
;;
;; The arguments are all evaluated before any of them is stored, which is what makes
;; `(f (g b) (h a))` safe when the new `a` is computed from the old `b` and vice versa.
;;
;; `:c::TC` is the context: the name and arity of the function being compiled, and the address
;; to jump back to. A `name` of "" means "this is not a tail position", and every subexpression
;; that is not in tail position is compiled with `(:c::no-tail)`.
(:wat::core::defrecord :c::TC
  [name <- :wat::core::String  arity <- :wat::core::i64  target <- :wat::core::i64])

(:wat::core::defn :c::no-tail [] -> :c::TC (:c::TC :name "" :arity 0 :target 0))

(:wat::core::defn :c::tail-call? [tc <- :c::TC head <- :wat::core::String n <- :wat::core::i64] -> :wat::core::bool
  (:wat::core::and (:wat::core::not= (:c::TC/name tc) "")
    (:wat::core::and (:wat::core::= (:c::TC/name tc) head) (:wat::core::= (:c::TC/arity tc) n))))

;; pop the freshly computed arguments back over the incoming ones, last first
(:wat::core::defn :c::tail-store [k <- :wat::core::i64 n <- :wat::core::i64 o <- :c::Out] -> :c::Out
  (:wat::core::if (:wat::core::>= k n) o
    (:c::tail-store (:wat::core::+ k 1) n
      (:c::emit o (:wat::string::concat "58" (:c::store (:wat::core::+ 16 (:wat::core::* 8 k))))))))

;; ---------------------------------------------------------------- expressions

(:wat::core::defn :c::expr [a <- :wat::WatAST o <- :c::Out env <- :c::Env fns <- :c::Fns
                            rt <- :wat::core::i64 tb <- :wat::core::i64 slot <- :wat::core::i64 tc <- :c::TC] -> :c::Out
  (:wat::core::let [k (:c::kind a)]
    (:wat::core::cond
      ((:wat::core::= k "int") (:c::emit o (:c::mov-rax (:c::to-int (:wat::core::ast->source a)))))
      ((:wat::core::= k "symbol")
        (:wat::core::let [d (:c::lookup env (:wat::core::ast->source a) (:wat::core::- (:wat::core::length env) 1))]
          (:wat::core::if (:wat::core::= d 999999) (:c::fail "name" a) (:c::emit o (:c::load d)))))
      ;; nil is a machine zero and a bool is 0 or 1, which is already what a comparison leaves
      ;; in rax -- so both are literals, and only `println` has to know which is which
      ((:wat::core::= k "nil") (:c::emit o (:c::mov-rax 0)))
      ((:wat::core::= k "bool")
        (:c::emit o (:c::mov-rax
          (:wat::core::if (:wat::core::= (:wat::core::ast->source a) "true") 1 0))))
      ((:wat::core::= k "string") (:c::str-lit a o tb))
      ((:wat::core::= k "list") (:c::form a o env fns rt tb slot tc))
      (:else (:c::fail "expression" a)))))

(:wat::core::defn :c::form [a <- :wat::WatAST o <- :c::Out env <- :c::Env fns <- :c::Fns
                            rt <- :wat::core::i64 tb <- :wat::core::i64 slot <- :wat::core::i64 tc <- :c::TC] -> :c::Out
  (:wat::core::let [ks (:wat::core::ast->children a)]
    (:wat::core::if (:wat::core::= (:wat::core::length ks) 0) (:c::fail "empty form" a)
      (:wat::core::let [head (:wat::core::ast->source (:wat::core::nth ks 0))
                        op (:c::binop head)]
        (:wat::core::cond
          ((:c::if? head) (:c::if-form ks a o env fns rt tb slot tc))
          ((:c::do? head) (:c::seq ks 1 o env fns rt tb slot tc))
          ;; a no-argument syscall: the number goes in rax, the result comes back in rax
          ((:wat::core::>= (:c::syscall-nr head) 0)
            (:wat::core::if (:wat::core::not= (:wat::core::length ks) 1) (:c::fail "syscall arity" a)
              (:c::emit o (:wat::string::concat (:c::mov-rax (:c::syscall-nr head)) "0f05"))))
          ;; exit(status): the argument is computed, then moved into rdi
          ((:c::exit? head)
            (:wat::core::if (:wat::core::not= (:wat::core::length ks) 2) (:c::fail "exit arity" a)
              (:c::emit (:c::expr (:wat::core::nth ks 1) o env fns rt tb slot (:c::no-tail))
                (:wat::string::concat (:c::mov-rdi-rax) (:c::mov-rax 60) "0f05"))))
;; mmap(NULL, len, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0)
          ;; -- the only way to get writable memory, since the one PT_LOAD is read+execute
          ((:c::mmap? head)
            (:wat::core::if (:wat::core::not= (:wat::core::length ks) 2) (:c::fail "mmap arity" a)
              (:c::emit (:c::expr (:wat::core::nth ks 1) o env fns rt tb slot (:c::no-tail))
                (:wat::string::concat
                  (:wat::string::concat (:c::mov-rsi-rax) (:c::mov-rdi 0))
                  (:wat::string::concat (:c::mov-rdx 3) (:c::mov-r10 34))
                  (:wat::string::concat (:c::mov-r8 -1) (:c::mov-r9 0))
                  (:wat::string::concat (:c::mov-rax 9) "0f05")))))
          ;; clone(CLONE_VM|CLONE_FS|CLONE_FILES|SIGCHLD, stack, 0, 0, 0)
          ;;
          ;; CLONE_VM is what makes this a THREAD -- the child shares the address space, so a
          ;; poke on one side is visible on the other. SIGCHLD rather than CLONE_THREAD is what
          ;; keeps it waitable with the same wait4 the fork program uses: a thread proper is not
          ;; a child in wait's sense, and this compiler has no futex.
          ((:c::clone? head)
            (:wat::core::if (:wat::core::not= (:wat::core::length ks) 2) (:c::fail "clone arity" a)
              (:c::emit (:c::expr (:wat::core::nth ks 1) o env fns rt tb slot (:c::no-tail))
                (:wat::string::concat
                  (:wat::string::concat (:c::mov-rsi-rax) (:c::mov-rdi 1809))
                  (:wat::string::concat (:c::mov-rdx 0) (:c::mov-r10 0) (:c::mov-r8 0))
                  (:wat::string::concat (:c::mov-rax 56) "0f05")))))
          ;; peek and poke: eight bytes at an address, which is all the memory model there is
          ((:c::peek? head)
            (:wat::core::if (:wat::core::not= (:wat::core::length ks) 2) (:c::fail "peek arity" a)
              (:c::emit (:c::expr (:wat::core::nth ks 1) o env fns rt tb slot (:c::no-tail)) "488b00")))
          ((:c::poke? head)
            (:wat::core::if (:wat::core::not= (:wat::core::length ks) 3) (:c::fail "poke arity" a)
              (:wat::core::let
                [o1 (:c::emit (:c::expr (:wat::core::nth ks 1) o env fns rt tb slot (:c::no-tail)) "50")
                 o2 (:c::expr (:wat::core::nth ks 2) o1 env fns rt tb slot (:c::no-tail))]
                (:c::emit o2 (:wat::string::concat "4889c1" "58" "488908")))))
          ;; wait4(-1, &status, 0, NULL) -- reap any one child and answer its raw STATUS, which is
          ;; more useful than the pid: `(rem (quot st 256) 256)` is the exit code. Sixteen bytes
          ;; of scratch are taken off rsp for the status word and given straight back.
          ((:c::wait? head)
            (:wat::core::if (:wat::core::not= (:wat::core::length ks) 1) (:c::fail "wait arity" a)
              (:c::emit o (:wat::string::concat
                (:c::sub-rsp 16)
                (:wat::string::concat (:c::mov-rdi -1) "4889e6")      ;; rsi = rsp
                (:wat::string::concat (:c::mov-rdx 0) (:c::mov-r10 0))
                (:wat::string::concat (:c::mov-rax 61) "0f05")
                (:wat::string::concat "488b0424" (:c::add-rsp 16))))))
          ;; string concatenation: a left fold through `str_cat`, which is the only thing the
          ;; compiler emits that allocates. `length` is a peek at the header.
          ((:c::concat? head)
            (:wat::core::if (:wat::core::< (:wat::core::length ks) 3) (:c::fail "concat arity" a)
              (:c::cat-fold ks 2 (:c::expr (:wat::core::nth ks 1) o env fns rt tb slot (:c::no-tail))
                env fns rt tb slot)))
          ((:c::strlen? head)
            (:wat::core::if (:wat::core::not= (:wat::core::length ks) 2) (:c::fail "length arity" a)
              (:c::emit (:c::expr (:wat::core::nth ks 1) o env fns rt tb slot (:c::no-tail)) "488b00")))
          ((:c::let? head) (:c::let-form ks a o env fns rt tb slot tc))
          ((:c::println? head) (:c::print-form ks a o env fns rt tb slot))
          ((:wat::core::not (:wat::core::= op ""))
            (:wat::core::if (:wat::core::< (:wat::core::length ks) 3) (:c::fail "operator arity" a)
              (:c::fold op ks 2 (:c::expr (:wat::core::nth ks 1) o env fns rt tb slot (:c::no-tail)) env fns rt tb slot)))
          ((:wat::core::>= (:c::fn-addr fns head 0) 0) (:c::call-user ks head o env fns rt tb slot tc))
          (:else (:c::fail "call" a)))))))

;; left fold: the first argument lands in rax, and each one after it is pushed, computed and
;; popped back -- the stack discipline a compiler without a register allocator has to use
(:wat::core::defn :c::fold [op <- :wat::core::String ks <- :c::Kids i <- :wat::core::i64
                            o <- :c::Out env <- :c::Env fns <- :c::Fns
                            rt <- :wat::core::i64 tb <- :wat::core::i64 slot <- :wat::core::i64] -> :c::Out
  (:wat::core::if (:wat::core::>= i (:wat::core::length ks)) o
    (:wat::core::let
      [o1 (:c::emit o "50")                                   ;; push rax
       o2 (:c::expr (:wat::core::nth ks i) o1 env fns rt tb slot (:c::no-tail))
       o3 (:c::emit o2 "4889c1")                              ;; mov rcx, rax
       o4 (:c::emit o3 "58")                                  ;; pop rax
       o5 (:c::emit o4 (:c::op-hex op))]
      (:c::fold op ks (:wat::core::+ i 1) o5 env fns rt tb slot))))

;; the same shape, with a call where the arithmetic fold has an instruction
(:wat::core::defn :c::cat-fold [ks <- :c::Kids i <- :wat::core::i64
                                o <- :c::Out env <- :c::Env fns <- :c::Fns
                                rt <- :wat::core::i64 tb <- :wat::core::i64 slot <- :wat::core::i64] -> :c::Out
  (:wat::core::if (:wat::core::>= i (:wat::core::length ks)) o
    (:wat::core::let
      [o1 (:c::emit o "50")                                   ;; push rax
       o2 (:c::expr (:wat::core::nth ks i) o1 env fns rt tb slot (:c::no-tail))
       o3 (:c::emit o2 "4889c1")                              ;; mov rcx, rax
       o4 (:c::emit o3 "58")                                  ;; pop rax
       o5 (:c::call o4 (:c::at-cat rt))]
      (:c::cat-fold ks (:wat::core::+ i 1) o5 env fns rt tb slot))))

;; ---------------------------------------------------------------- if

(:wat::core::defn :c::if-form [ks <- :c::Kids a <- :wat::WatAST o <- :c::Out env <- :c::Env fns <- :c::Fns
                               rt <- :wat::core::i64 tb <- :wat::core::i64 slot <- :wat::core::i64 tc <- :c::TC] -> :c::Out
  (:wat::core::if (:wat::core::not= (:wat::core::length ks) 4) (:c::fail "if arity" a)
    (:wat::core::let
      [o1 (:c::expr (:wat::core::nth ks 1) o env fns rt tb slot (:c::no-tail))
       o2 (:c::emit o1 "4885c0")                       ;; test rax, rax
       o3 (:c::emit o2 "0f8400000000")                 ;; jz <patched below>
       jz-at (:wat::core::- (:c::codelen o3) 4)
       o4 (:c::expr (:wat::core::nth ks 2) o3 env fns rt tb slot tc)
       o5 (:c::emit o4 "e900000000")                   ;; jmp <patched below>
       jmp-at (:wat::core::- (:c::codelen o5) 4)
       o6 (:c::patch o5 jz-at (:asm::le (:wat::core::- (:c::codelen o5) (:wat::core::+ jz-at 4)) 4))
       o7 (:c::expr (:wat::core::nth ks 3) o6 env fns rt tb slot tc)]
      (:c::patch o7 jmp-at (:asm::le (:wat::core::- (:c::codelen o7) (:wat::core::+ jmp-at 4)) 4)))))

;; ---------------------------------------------------------------- let

(:wat::core::defrecord :c::BindR [o <- :c::Out  env <- :c::Env  slot <- :wat::core::i64])

(:wat::core::defn :c::bind-each [bs <- :c::Kids i <- :wat::core::i64 o <- :c::Out env <- :c::Env
                                 fns <- :c::Fns rt <- :wat::core::i64 tb <- :wat::core::i64
                                 slot <- :wat::core::i64] -> :c::BindR
  (:wat::core::if (:wat::core::>= i (:wat::core::length bs)) (:c::BindR :o o :env env :slot slot)
    (:wat::core::let
      [name (:wat::core::ast->source (:wat::core::nth bs i))
       ;; the initialiser is compiled in the OUTER scope, which is what makes `let` not `letrec`
       o1 (:c::expr (:wat::core::nth bs (:wat::core::+ i 1)) o env fns rt tb slot (:c::no-tail))
       disp (:wat::core::* -8 (:wat::core::+ slot 1))
       o2 (:c::emit o1 (:c::store disp))]
      (:c::bind-each bs (:wat::core::+ i 2) o2
        (:wat::core::conj env
          (:c::Bind :name name :disp disp
                    :ty (:c::type-of (:wat::core::nth bs (:wat::core::+ i 1)) env fns)))
        fns rt tb (:wat::core::+ slot 1)))))

(:wat::core::defn :c::let-form [ks <- :c::Kids a <- :wat::WatAST o <- :c::Out env <- :c::Env fns <- :c::Fns
                                rt <- :wat::core::i64 tb <- :wat::core::i64 slot <- :wat::core::i64 tc <- :c::TC] -> :c::Out
  (:wat::core::if (:wat::core::< (:wat::core::length ks) 3) (:c::fail "let arity" a)
    (:wat::core::let [bs (:wat::core::ast->children (:wat::core::nth ks 1))]
      (:wat::core::if (:wat::core::not= (:wat::core::rem (:wat::core::length bs) 2) 0) (:c::fail "let bindings" a)
        (:wat::core::let [r (:c::bind-each bs 0 o env fns rt tb slot)]
          ;; the bindings go out of scope with the body, so the env is not carried back out
          (:c::seq ks 2 (:c::BindR/o r) (:c::BindR/env r) fns rt tb (:c::BindR/slot r) tc))))))

;; ---------------------------------------------------------------- sequences, and the heap
;;
;; ## Why a bump allocator can free
;;
;; A sequence's last form is its value; every form BEFORE it has its value thrown away. So
;; whatever a non-final form allocated is garbage the instant it finishes -- and with a bump
;; allocator, freeing all of it is one instruction: put r15 back where it was.
;;
;;   push r15 ; push r15        mark
;;   <the statement>
;;   pop r15 ; pop r15          release
;;
;; Twice, because the frame is kept 16-byte aligned and one push would tip it. Eight bytes of
;; code per statement, and it nests without any bookkeeping, because the marks live on the stack.
;;
;; ## Why this is sound, and exactly where it stops
;;
;; The release is only safe if nothing that outlives the statement can be holding a pointer into
;; what it allocated. In this language there are exactly two ways a pointer can be stored:
;;
;;   * a `let` slot -- written inside the statement, and out of scope when it ends, because
;;     `:c::let-form` does not carry its environment back out past its body. Safe.
;;   * `poke` -- an arbitrary address, which the statement can hand to anyone. NOT safe.
;;
;; So a statement containing a `poke` anywhere inside it is not released. The test is a substring
;; of the statement's own source, which is crude in the direction that costs nothing: a false
;; positive only declines to free memory.
;;
;; A returned value is never released, because the final form is never marked -- which is what
;; makes `(defn f [] :- wat.type/String (wat.string/concat ...))` keep working.
;;
;; ## What it does not do
;;
;; Anything whose allocation ESCAPES upward still accumulates, and `(user/stars 40 "")` in
;; elf/src/strings.wat is a deliberate example: each level's result is the next level's argument,
;; so every intermediate string is live until the outermost one is. Freeing those needs
;; reachability, not scope -- a collector, or a caller-side release at every call whose return
;; type is not a pointer. The second is the next thing to build and is the same idea one level
;; up; the first is a different program.

(:wat::core::defn :c::releasable? [a <- :wat::WatAST] -> :wat::core::bool
  (:wat::core::not (:wat::string::contains? (:wat::core::ast->source a) "poke")))

;; a sequence of forms; the last one's value is the value of the whole, and every form before it
;; gives its allocations back
(:wat::core::defn :c::seq [ks <- :c::Kids i <- :wat::core::i64 o <- :c::Out env <- :c::Env fns <- :c::Fns
                           rt <- :wat::core::i64 tb <- :wat::core::i64 slot <- :wat::core::i64 tc <- :c::TC] -> :c::Out
  (:wat::core::if (:wat::core::>= i (:wat::core::length ks)) o
    (:wat::core::let
      [a (:wat::core::nth ks i)
       drop? (:wat::core::and (:wat::core::< i (:wat::core::- (:wat::core::length ks) 1))
                              (:c::releasable? a))
       o1 (:wat::core::if drop? (:c::emit o "41574157") o)
       last? (:wat::core::= i (:wat::core::- (:wat::core::length ks) 1))
       o2 (:c::expr a o1 env fns rt tb slot (:wat::core::if last? tc (:c::no-tail)))
       o3 (:wat::core::if drop? (:c::emit o2 "415f415f") o2)]
      (:c::seq ks (:wat::core::+ i 1) o3 env fns rt tb slot tc))))

;; ---------------------------------------------------------------- println

(:wat::core::defn :c::print-form [ks <- :c::Kids a <- :wat::WatAST o <- :c::Out env <- :c::Env fns <- :c::Fns
                                  rt <- :wat::core::i64 tb <- :wat::core::i64 slot <- :wat::core::i64] -> :c::Out
  (:wat::core::if (:wat::core::not= (:wat::core::length ks) 2) (:c::fail "println arity" a)
    (:wat::core::let [arg (:wat::core::nth ks 1)
                      ty (:c::type-of arg env fns)]
      (:wat::core::cond
        ;; a literal is its own EDN rendering, so it goes out as bytes with no runtime at all
        ((:wat::core::= (:c::kind arg) "string") (:c::print-string arg o tb))
        ((:wat::core::= ty "str") (:c::call (:c::expr arg o env fns rt tb slot (:c::no-tail)) (:c::at-str rt)))
        ;; `(println (> 3 2))` prints `true`, not `1`. The type pass is the only thing standing
        ;; between the compiler and a SILENT disagreement with the interpreter here, which is why
        ;; every one of these four paths has a program in elf/src that exercises it.
        ((:wat::core::= ty "bool") (:c::call (:c::expr arg o env fns rt tb slot (:c::no-tail)) (:c::at-bool rt)))
        ((:wat::core::= ty "nil") (:c::print-nil (:c::expr arg o env fns rt tb slot (:c::no-tail))))
        (:else (:c::call (:c::expr arg o env fns rt tb slot (:c::no-tail)) (:c::at-i64 rt)))))))

;; nil renders as four bytes and never varies, so it is written straight out of the stack rather
;; than costing the output a runtime routine: `mov dword [rsp], "nil\n"` and one write.
(:wat::core::defn :c::print-nil [o <- :c::Out] -> :c::Out
  (:c::emit o (:wat::string::concat
    (:c::sub-rsp 16)
    "c704246e696c0a"                                   ;; mov dword [rsp], 0x0a6c696e
    (:wat::string::concat "4889e6" (:c::mov-rdx 4))     ;; rsi = rsp ; rdx = 4
    (:wat::string::concat (:c::mov-rax 1) (:c::mov-rdi 1) "0f05")
    (:c::add-rsp 16))))

;; `:wat::kernel::println` renders a String as EDN -- `(println "a\nb")` writes `"a\nb"` and a
;; newline, quotes kept and the escape NOT expanded -- so the faithful compilation of a string
;; literal is its SOURCE TEXT, verbatim. The first version stripped the quotes and unescaped,
;; and the differential test against the interpreter caught it on the first run.
(:wat::core::defn :c::print-string [a <- :wat::WatAST o <- :c::Out tb <- :wat::core::i64] -> :c::Out
  (:wat::core::let
    [text (:wat::string::concat (:wat::core::ast->source a) "\n")
     addr (:wat::core::+ tb (:wat::core::/ (:wat::string::length (:c::Out/tail o)) 2))
     o1 (:wat::core::assoc o :tail (:wat::string::concat (:c::Out/tail o) (:asm::ascii text 0 "")))]
    (:c::emit (:c::emit (:c::emit (:c::emit o1 (:c::mov-rax 1)) (:c::mov-rdi 1))
                (:wat::string::concat (:c::mov-rsi addr) (:c::mov-rdx (:wat::string::length text))))
      "0f05")))

;; ---------------------------------------------------------------- calling a user function
;;
;; Arguments are pushed left to right, so the last one is nearest the top of the stack. Inside
;; the callee, rbp points at the saved rbp, [rbp+8] is the return address, and argument i of n
;; sits at [rbp + 16 + 8*(n-1-i)]. The caller pops them after the call.

(:wat::core::defn :c::push-args [ks <- :c::Kids i <- :wat::core::i64 o <- :c::Out env <- :c::Env
                                 fns <- :c::Fns rt <- :wat::core::i64 tb <- :wat::core::i64
                                 slot <- :wat::core::i64] -> :c::Out
  (:wat::core::if (:wat::core::>= i (:wat::core::length ks)) o
    (:c::push-args ks (:wat::core::+ i 1)
      (:c::emit (:c::expr (:wat::core::nth ks i) o env fns rt tb slot (:c::no-tail)) "50") env fns rt tb slot)))

(:wat::core::defn :c::call-user [ks <- :c::Kids head <- :wat::core::String o <- :c::Out env <- :c::Env
                                 fns <- :c::Fns rt <- :wat::core::i64 tb <- :wat::core::i64
                                 slot <- :wat::core::i64 tc <- :c::TC] -> :c::Out
  (:wat::core::let [n (:wat::core::- (:wat::core::length ks) 1)
                    o1 (:c::push-args ks 1 o env fns rt tb slot)]
    (:wat::core::if (:c::tail-call? tc head n)
      ;; a self call in tail position: overwrite the incoming arguments and go round again, on
      ;; the SAME frame, so a tail-recursive loop runs in constant stack
      (:wat::core::let [o2 (:c::tail-store 0 n o1)]
        (:c::emit o2 (:wat::string::concat "e9"
          (:asm::le (:wat::core::- (:c::TC/target tc) (:wat::core::+ (:c::here o2) 5)) 4))))
      (:wat::core::let [o2 (:c::call o1 (:c::fn-addr fns head 0))]
        (:wat::core::if (:wat::core::= n 0) o2
          (:c::emit o2 (:c::add-rsp (:wat::core::* 8 n))))))))

;; ---------------------------------------------------------------- compiling one function

(:wat::core::defn :c::param-env [pv <- :c::Kids i <- :wat::core::i64 n <- :wat::core::i64
                                 env <- :c::Env] -> :c::Env
  ;; the parameter vector reads `name :- type` per parameter, so names are every third child
  (:wat::core::if (:wat::core::>= i (:wat::core::length pv)) env
    (:c::param-env pv (:wat::core::+ i 3) n
      (:wat::core::conj env
        (:c::Bind :name (:wat::core::ast->source (:wat::core::nth pv i))
                  :ty (:c::ty-of-node (:wat::core::nth pv (:wat::core::+ i 2)))
                  :disp (:wat::core::+ 16 (:wat::core::* 8 (:wat::core::- (:wat::core::- n 1)
                                                             (:wat::core::/ i 3)))))))))

(:wat::core::defn :c::nparams [pv <- :c::Kids] -> :wat::core::i64
  (:wat::core::if (:wat::core::= (:wat::core::length pv) 0) 0
    (:wat::core::+ (:wat::core::/ (:wat::core::- (:wat::core::length pv) 1) 3) 1)))

(:wat::core::defn :c::compile-fn [node <- :wat::WatAST base <- :wat::core::i64 fns <- :c::Fns
                                  rt <- :wat::core::i64 tb <- :wat::core::i64
                                  tail-in <- :wat::core::String] -> :c::Out
  (:wat::core::let
    [ks (:wat::core::ast->children node)
     pv (:wat::core::ast->children (:wat::core::nth ks 2))
     n (:c::nparams pv)
     env (:c::param-env pv 0 n (:wat::core::Vector :- [:c::Bind]))
     start (:c::body-start ks 3)
     slots (:c::slots-body ks start 0)
     ;; the System V ABI wants rsp 16-byte aligned at a call, so the frame is rounded up
     frame (:wat::core::* 8 (:wat::core::if (:wat::core::= (:wat::core::rem slots 2) 0) slots
                              (:wat::core::+ slots 1)))
     o0 (:c::Out :base base :code "" :tail tail-in)
     o1 (:c::emit o0 (:wat::string::concat "55" "4889e5" (:c::sub-rsp frame)))
     ;; push rbp (1) + mov rbp,rsp (3) + sub rsp,imm32 (7) = 11: the top of the body
     ;;
     ;; ...unless the function clones. A tail call REUSES the frame, which is sound only while
     ;; the frame is private to this thread -- and `clone` hands a second thread an rbp pointing
     ;; straight at it (the child gets a fresh rsp but inherits rbp). elf/native/threads4.wat is
     ;; the program that proves it: with its `user/spawn` tail call eliminated, the parent
     ;; overwrote `i` while four children were still reading it, and the answer fell from 1000
     ;; to 400. Same shape as `:c::releasable?` and `poke`, and the same lesson: the intrinsics
     ;; break invariants the rest of the compiler is entitled to assume about wat.
     tc (:wat::core::if (:wat::string::contains? (:wat::core::ast->source node) "clone")
          (:c::no-tail)
          (:c::TC :name (:wat::core::ast->source (:wat::core::nth ks 1)) :arity n
                  :target (:wat::core::+ base 11)))
     o2 (:c::seq ks start o1 env fns rt tb 0 tc)]
    (:c::emit o2 "c9c3")))                       ;; leave ; ret

;; ---------------------------------------------------------------- the driver
;;
;; Two passes over the WHOLE program, not just one function: a call needs the callee's address,
;; and a callee's address depends on the length of everything before it. Pass one compiles with
;; every address zero, purely to measure; pass two compiles again with the real table. Every
;; immediate and every displacement is fixed width, so the two passes are the same length -- and
;; the compiler asserts that, function by function.

(:wat::core::defn :c::forms-of [src <- :wat::core::String] -> :wat::WatAST
  (:wat::core::match (:wat::core::read-string src)
    [:wat::core::ReadOutcome.Forms {:forms fs} fs]
    [:wat::core::ReadOutcome.Malformed {:cause e}
      (:wat::kernel::assertion-failed!
        :message (:wat::string::concat "compile: unreadable source: " (:wat::core::Error/message e)))]))

(:wat::core::defn :c::collect [tops <- :c::Kids i <- :wat::core::i64 acc <- :c::Fns] -> :c::Fns
  (:wat::core::if (:wat::core::>= i (:wat::core::length tops)) acc
    (:wat::core::let [t (:wat::core::nth tops i)
                      ks (:wat::core::ast->children t)]
      (:wat::core::if (:wat::core::or (:wat::core::not (:wat::core::= (:c::kind t) "list"))
                        (:wat::core::not (:c::defn? (:wat::core::ast->source (:wat::core::nth ks 0)))))
        (:wat::kernel::assertion-failed!
          :message (:wat::string::concat "compile: only defn is allowed at the top level: "
                     (:wat::core::ast->source t)))
        (:c::collect tops (:wat::core::+ i 1)
          (:wat::core::conj acc
            (:c::Fn :name (:wat::core::ast->source (:wat::core::nth ks 1)) :node t :addr 0
                    :ret (:c::ty-of-node
                           (:wat::core::nth ks (:wat::core::- (:c::body-start ks 3) 1))))))))))

;; one pass over every function: each is compiled at the address the table says, and the lengths
;; come back so the next table can be built
(:wat::core::defrecord :c::PassR
  [code <- :wat::core::String  tail <- :wat::core::String
   lens <- (:wat::core::Vector :- [:wat::core::i64])])

(:wat::core::defn :c::pass [fns <- :c::Fns i <- :wat::core::i64 rt <- :wat::core::i64 tb <- :wat::core::i64
                            acc <- :c::PassR] -> :c::PassR
  (:wat::core::if (:wat::core::>= i (:wat::core::length fns)) acc
    (:wat::core::let
      [f (:wat::core::nth fns i)
       o (:c::compile-fn (:c::Fn/node f) (:c::Fn/addr f) fns rt tb (:c::PassR/tail acc))]
      (:c::pass fns (:wat::core::+ i 1) rt tb
        (:c::PassR :code (:wat::string::concat (:c::PassR/code acc) (:c::Out/code o))
                   :tail (:c::Out/tail o)
                   :lens (:wat::core::conj (:c::PassR/lens acc) (:c::codelen o)))))))

(:wat::core::defn :c::empty-pass [] -> :c::PassR
  (:c::PassR :code "" :tail "" :lens (:wat::core::Vector :- [:wat::core::i64])))

;; the entry stub, and the only code not compiled from a defn: mmap a heap, park its address in
;; r15, call main, exit(0). 94 bytes.
;;
;; **r15 is the whole memory model.** It is the bump pointer, it is callee-saved in the System V
;; ABI, and nothing here ever calls anything this compiler did not emit -- so one register
;; reserved for the program's lifetime is the entire allocator. There is no free, no collector
;; and no bounds check: the heap is a megabyte, and a program that wants more gets a
;; segmentation fault rather than an error message.
(:wat::core::defn :c::heap-bytes [] -> :wat::core::i64 1048576)

(:wat::core::defn :c::stub-len [] -> :wat::core::i64 94)

(:wat::core::defn :c::stub [main-addr <- :wat::core::i64] -> :wat::core::String
  (:wat::core::let
    [o (:c::Out :base (:asm::entry) :code "" :tail "")
     o1 (:c::emit o (:wat::string::concat
          (:wat::string::concat (:c::mov-rax 9) (:c::mov-rdi 0) (:c::mov-rsi (:c::heap-bytes)))
          (:wat::string::concat (:c::mov-rdx 3) (:c::mov-r10 34))
          (:wat::string::concat (:c::mov-r8 -1) (:c::mov-r9 0))
          (:wat::string::concat "0f05" "4989c7")))]        ;; syscall ; mov r15, rax
    (:c::Out/code (:c::emit (:c::call o1 main-addr)
                    (:wat::string::concat (:c::mov-rax 60) "31ff" "0f05")))))

;; place every function end to end after the stub
(:wat::core::defn :c::place [fns <- :c::Fns lens <- (:wat::core::Vector :- [:wat::core::i64])
                             i <- :wat::core::i64 at <- :wat::core::i64 acc <- :c::Fns] -> :c::Fns
  (:wat::core::if (:wat::core::>= i (:wat::core::length fns)) acc
    (:c::place fns lens (:wat::core::+ i 1) (:wat::core::+ at (:wat::core::nth lens i))
      (:wat::core::conj acc (:wat::core::assoc (:wat::core::nth fns i) :addr at)))))

(:wat::core::defn :c::total [lens <- (:wat::core::Vector :- [:wat::core::i64]) i <- :wat::core::i64
                             acc <- :wat::core::i64] -> :wat::core::i64
  (:wat::core::if (:wat::core::>= i (:wat::core::length lens)) acc
    (:c::total lens (:wat::core::+ i 1) (:wat::core::+ acc (:wat::core::nth lens i)))))

(:wat::core::defn :c::same-lens [a <- (:wat::core::Vector :- [:wat::core::i64])
                                 b <- (:wat::core::Vector :- [:wat::core::i64]) i <- :wat::core::i64] -> :wat::core::nil
  (:wat::core::if (:wat::core::>= i (:wat::core::length a)) nil
    (:wat::core::do (:wat::test::assert-eq (:wat::core::nth a i) (:wat::core::nth b i))
                    (:c::same-lens a b (:wat::core::+ i 1)))))

(:wat::core::defn :c::compile [src-path <- :wat::core::String out-path <- :wat::core::String] -> :wat::core::nil
  (:wat::core::let
    [tops (:wat::core::ast->children (:c::forms-of (:wat::io::read-file src-path)))
     fns0 (:c::collect tops 0 (:wat::core::Vector :- [:c::Fn]))

     ;; PASS ONE: nothing has an address yet, and nothing needs one
     p1 (:c::pass fns0 0 0 0 (:c::empty-pass))
     code-total (:c::total (:c::PassR/lens p1) 0 0)

     ;; now every address follows from the lengths
     fns1 (:c::place fns0 (:c::PassR/lens p1) 0
            (:wat::core::+ (:asm::entry) (:c::stub-len)) (:wat::core::Vector :- [:c::Fn]))
     rt-addr (:wat::core::+ (:wat::core::+ (:asm::entry) (:c::stub-len)) code-total)
     tail-base (:wat::core::+ rt-addr (:wat::core::/ (:wat::string::length (:c::runtime)) 2))
     main-addr (:c::fn-addr fns1 "user/main" 0)

     ;; PASS TWO: now they do
     p2 (:c::pass fns1 0 rt-addr tail-base (:c::empty-pass))
     text (:wat::string::concat (:c::stub main-addr) (:c::PassR/code p2) (:c::runtime))
     written (:asm::link out-path text (:c::PassR/tail p2))
     int (:wat::core::fn [n <- :wat::core::i64] -> :wat::core::String (:wat::i64::to-string n))]
    (:wat::core::do
      (:wat::core::if (:wat::core::< main-addr 0)
        (:wat::kernel::assertion-failed! :message "compile: no user/main") nil)
      ;; the invariant the two-pass technique rests on
      (:c::same-lens (:c::PassR/lens p1) (:c::PassR/lens p2) 0)
      (:wat::test::assert-eq (:wat::string::length (:c::PassR/tail p1))
                             (:wat::string::length (:c::PassR/tail p2)))
      (:wat::kernel::println
        (:wat::string::concat "compile: " (:asm::pad src-path 22) " -> " (:asm::pad out-path 24)
          (:asm::pad (int written) 5) " bytes   fns " (:asm::pad (int (:wat::core::length fns0)) 3)
          "  code " (:asm::pad (int code-total) 5)
          "  data " (:asm::pad (int (:wat::core::/ (:wat::string::length (:c::PassR/tail p2)) 2)) 4)
          "  verified")))))

(:wat::core::defn :user::main [] -> :wat::core::nil
  (:c::compile "elf/bad/nonascii.wat" "elf/out/bad.elf"))
